/**
 * Canonical semantic mappings for the authored answer-first query hub.
 *
 * These mappings are authoritative. The sections deliberately combine several
 * clinical terms, so keyword heuristics must never decide their primary entity.
 */
export const authoredAnswerMappings = Object.freeze([
  {
    sectionId: 'best-aesthetic-doctor-kermanshah-answers',
    question: 'پاسخ مستقیم به جست‌وجوهای «بهترین دکتر زیبایی در کرمانشاه»',
    queryVariants: [],
    conceptIds: [],
    procedureIds: [],
    primaryConceptId: null,
    primaryProcedureId: null,
    primaryIntentIds: [],
    dimensionId: 'doctor-selection',
    kind: 'hub',
  },
  {
    sectionId: 'best-aesthetic-doctor-kermanshah',
    question: 'بهترین دکتر زیبایی کرمانشاه را چگونه انتخاب کنیم؟',
    queryVariants: ['بهترین دکتر زیبایی کرمانشاه', 'بهترین پزشک زیبایی کرمانشاه'],
    conceptIds: [],
    procedureIds: [],
    primaryConceptId: null,
    primaryProcedureId: null,
    primaryIntentIds: [],
    dimensionId: 'doctor-selection',
    kind: 'question',
  },
  {
    sectionId: 'best-botox-doctor-kermanshah',
    question: 'بهترین دکتر بوتاکس در کرمانشاه چه تفاوتی باید ایجاد کند؟',
    queryVariants: ['بهترین دکتر بوتاکس کرمانشاه', 'بهترین پزشک تزریق بوتاکس در کرمانشاه'],
    conceptIds: ['botox-glabella', 'botox-forehead', 'botox-crows-feet', 'botox-masseter', 'botox-gummy-smile'],
    procedureIds: ['botulinum-toxin'],
    primaryConceptId: null,
    primaryProcedureId: 'botulinum-toxin',
    primaryIntentIds: [],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-filler-doctor-kermanshah',
    question: 'بهترین دکتر فیلر در کرمانشاه چگونه از پُرکردن بی‌هدف جلوگیری می‌کند؟',
    queryVariants: ['بهترین دکتر فیلر کرمانشاه', 'بهترین پزشک تزریق ژل در کرمانشاه'],
    conceptIds: ['filler-chin', 'filler-jawline', 'filler-lips', 'filler-cheek', 'filler-dissolving'],
    procedureIds: ['dermal-filler'],
    primaryConceptId: null,
    primaryProcedureId: 'dermal-filler',
    primaryIntentIds: [],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-lip-filler-doctor-kermanshah',
    question: 'بهترین دکتر فیلر لب در کرمانشاه چه چیزی را قبل از حجم می‌بیند؟',
    queryVariants: ['بهترین دکتر فیلر لب کرمانشاه', 'بهترین پزشک تزریق ژل لب در کرمانشاه'],
    conceptIds: ['filler-lips'],
    procedureIds: ['dermal-filler'],
    primaryConceptId: 'filler-lips',
    primaryProcedureId: 'dermal-filler',
    primaryIntentIds: ['intent-filler-lips-best-doctor-local'],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-under-eye-filler-doctor-kermanshah',
    question: 'بهترین دکتر فیلر زیر چشم در کرمانشاه چه زمانی تزریق را رد می‌کند؟',
    queryVariants: ['بهترین دکتر فیلر زیر چشم کرمانشاه', 'بهترین پزشک تزریق ژل زیر چشم در کرمانشاه'],
    conceptIds: ['filler-under-eye'],
    procedureIds: ['dermal-filler'],
    primaryConceptId: 'filler-under-eye',
    primaryProcedureId: 'dermal-filler',
    primaryIntentIds: ['intent-filler-under-eye-best-doctor-local'],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-thread-lift-doctor-kermanshah',
    question: 'بهترین دکتر لیفت نخ در کرمانشاه چگونه صورت نخ‌ناپذیر را تشخیص می‌دهد؟',
    queryVariants: ['بهترین دکتر لیفت نخ کرمانشاه', 'بهترین پزشک نخ لیفت صورت در کرمانشاه'],
    conceptIds: ['thread-face', 'thread-jawline'],
    procedureIds: ['thread-lift'],
    primaryConceptId: null,
    primaryProcedureId: 'thread-lift',
    primaryIntentIds: [],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-acne-scar-subcision-doctor-kermanshah',
    question: 'بهترین دکتر درمان جای جوش و سابسیژن در کرمانشاه چه چیزی را تفکیک می‌کند؟',
    queryVariants: ['بهترین دکتر درمان جای جوش کرمانشاه', 'بهترین دکتر سابسیژن در کرمانشاه'],
    conceptIds: ['acne-scar-evaluation', 'subcision-rolling-scar', 'tca-cross'],
    procedureIds: ['acne-scar-treatment', 'subcision'],
    primaryConceptId: 'acne-scar-evaluation',
    primaryProcedureId: 'acne-scar-treatment',
    primaryIntentIds: ['intent-acne-scar-evaluation-best-doctor-local', 'intent-subcision-rolling-scar-best-doctor-local'],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-skin-rejuvenation-doctor-kermanshah',
    question: 'بهترین دکتر جوانسازی پوست در کرمانشاه چگونه روش را انتخاب می‌کند؟',
    queryVariants: ['بهترین دکتر جوانسازی پوست کرمانشاه', 'بهترین پزشک جوانسازی صورت در کرمانشاه'],
    conceptIds: ['skin-booster', 'prp-skin', 'mesotherapy-skin', 'microneedling', 'profhilo', 'jalupro', 'mesogel', 'mesobotox'],
    procedureIds: ['skin-rejuvenation', 'prp-skin-hair', 'mesotherapy'],
    primaryConceptId: null,
    primaryProcedureId: 'skin-rejuvenation',
    primaryIntentIds: [],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-hair-loss-prp-doctor-kermanshah',
    question: 'بهترین دکتر درمان ریزش مو و PRP در کرمانشاه از کجا شروع می‌کند؟',
    queryVariants: ['بهترین دکتر ریزش مو کرمانشاه', 'بهترین دکتر PRP مو در کرمانشاه'],
    conceptIds: ['hair-loss-diagnosis', 'androgenetic-alopecia', 'telogen-effluvium', 'prp-hair', 'mesotherapy-hair'],
    procedureIds: ['hair-loss-evaluation', 'prp-skin-hair', 'mesotherapy'],
    primaryConceptId: 'hair-loss-diagnosis',
    primaryProcedureId: 'hair-loss-evaluation',
    primaryIntentIds: ['intent-hair-loss-diagnosis-best-doctor-local', 'intent-prp-hair-best-doctor-local'],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
  {
    sectionId: 'best-submental-liposuction-doctor-kermanshah',
    question: 'بهترین دکتر ساکشن غبغب در کرمانشاه چه زمانی جراحی را منطقی می‌داند؟',
    queryVariants: ['بهترین دکتر ساکشن غبغب کرمانشاه', 'بهترین پزشک لیپوساکشن غبغب در کرمانشاه'],
    conceptIds: ['submental-liposuction-service', 'submental-fat-evaluation', 'chin-jaw-submental-combination'],
    procedureIds: ['submental-liposuction'],
    primaryConceptId: 'submental-liposuction-service',
    primaryProcedureId: 'submental-liposuction',
    primaryIntentIds: ['intent-submental-liposuction-service-best-doctor-local', 'intent-submental-fat-evaluation-best-doctor-local'],
    dimensionId: 'best-doctor-local',
    kind: 'question',
  },
]);

const mappingBySection = new Map(authoredAnswerMappings.map((entry) => [entry.sectionId, entry]));

export function authoredAnswerMappingFor(sectionId) {
  return mappingBySection.get(sectionId) ?? null;
}
