export const editorialReview = {
  id: 'editorial-review-2026-07-11',
  reviewedByEntityId: 'https://www.ghezelbaash.ir/#person',
  reviewerName: 'دکتر محمدسعید قزلباش',
  reviewerProfessionalName: 'دکتر سعید قزلباش',
  medicalRegistration: '167430',
  datePublished: '2026-07-10',
  dateModified: '2026-07-11',
  reviewScope: [
    'هم‌خوانی متن قابل مشاهده با هویت پزشک و کلینیک',
    'پوشش خدمات غیرجراحی، کم‌تهاجمی و جراحی‌های مرتبط',
    'اتصال Claim، Evidence، Answer، Search Intent و رسانه',
    'مرزبندی offered، evaluated و referral-context',
  ],
  responsibility: 'نویسنده، بازبین مسئول و انتیتی اصلی محتوای پزشکی',
};

export const authorityNetwork = [
  {
    id: 'irimc',
    layer: 'official-medical-identity',
    label: 'هویت رسمی پزشکی',
    name: 'سازمان نظام پزشکی جمهوری اسلامی ایران',
    url: 'https://membersearch.irimc.org/member/profile?id=9efaaf28-52ff-49ad-8d45-be6e48c4fa3e',
    role: 'تأیید نام و شماره نظام پزشکی ۱۶۷۴۳۰',
    entity: 'physician',
    evidenceTier: 1,
  },
  {
    id: 'orcid',
    layer: 'research-identity',
    label: 'شناسه پایدار پژوهشگر',
    name: 'ORCID',
    url: 'https://orcid.org/0009-0001-9346-8475',
    role: 'تفکیک هویت پژوهشی و اتصال آثار علمی',
    entity: 'physician',
    evidenceTier: 1,
  },
  {
    id: 'ncbi',
    layer: 'research-bibliography',
    label: 'کتاب‌شناسی علمی',
    name: 'NCBI Bibliography',
    url: 'https://www.ncbi.nlm.nih.gov/myncbi/saeed.ghezelbash.1/bibliography/public/',
    role: 'مسیر عمومی کتاب‌شناسی پژوهشی پزشک',
    entity: 'physician',
    evidenceTier: 1,
  },
  {
    id: 'wikidata-person',
    layer: 'public-knowledge-graph',
    label: 'گراف دانش عمومی پزشک',
    name: 'Wikidata Q140287622',
    url: 'https://www.wikidata.org/entity/Q140287622',
    role: 'حل انتیتی و نام‌های جایگزین پزشک',
    entity: 'physician',
    evidenceTier: 3,
  },
  {
    id: 'wikidata-clinic',
    layer: 'public-knowledge-graph',
    label: 'گراف دانش عمومی کلینیک',
    name: 'Wikidata Q140288589',
    url: 'https://www.wikidata.org/entity/Q140288589',
    role: 'حل انتیتی کلینیک و اتصال مکان به پزشک',
    entity: 'clinic',
    evidenceTier: 3,
  },
  {
    id: 'google-maps',
    layer: 'local-reputation-location',
    label: 'اعتبار مکانی و بازخورد عمومی',
    name: 'Google Maps',
    url: 'https://www.google.com/maps?cid=12350483144643112463',
    role: 'مکان، مسیریابی و snapshot امتیاز عمومی کلینیک',
    entity: 'clinic',
    evidenceTier: 2,
  },
  {
    id: 'huggingface-profile',
    layer: 'ai-public-profile',
    label: 'پروفایل عمومی AI/ML',
    name: 'Hugging Face Profile',
    url: 'https://huggingface.co/Ghezelbaash',
    role: 'اتصال وب‌سایت و هویت پزشک به اکوسیستم عمومی هوش مصنوعی',
    entity: 'physician',
    evidenceTier: 2,
  },
  {
    id: 'huggingface-dataset',
    layer: 'ai-readable-dataset',
    label: 'دیتاست عمومی AI-readable',
    name: 'Dr. Saeed Ghezelbash Entity Data',
    url: 'https://huggingface.co/datasets/doctor-ghezelbaash/dr-saeid-ghezelbaash-entity-data',
    role: 'توزیع عمومی داده‌های انتیتی، خدمات و positioning برای بازیابی ماشینی',
    entity: 'physician-clinic',
    evidenceTier: 2,
  },
  {
    id: 'github-repository',
    layer: 'structured-data-source',
    label: 'مخزن عمومی داده ساختاریافته',
    name: 'GitHub structured-data repository',
    url: 'https://github.com/medicaldoctor91/doctor-ghezelbaash',
    role: 'منبع عمومی نسخه‌پذیر برای داده‌های انتیتی و ساختاریافته',
    entity: 'physician-clinic',
    evidenceTier: 2,
  },
  {
    id: 'zenodo-doi',
    layer: 'archived-citation',
    label: 'آرشیو DOI پایدار',
    name: 'Zenodo DOI 10.5281/zenodo.18765169',
    url: 'https://doi.org/10.5281/zenodo.18765169',
    role: 'لایه آرشیو و استناد پایدار برای دارایی‌های داده‌ای',
    entity: 'physician-clinic',
    evidenceTier: 2,
  },
  {
    id: 'linkedin',
    layer: 'professional-profile',
    label: 'پروفایل حرفه‌ای بیرونی',
    name: 'LinkedIn',
    url: 'https://www.linkedin.com/in/saeed-ghezelbash-93310a96',
    role: 'حضور حرفه‌ای و تطبیق نام لاتین پزشک',
    entity: 'physician',
    evidenceTier: 2,
  },
  {
    id: 'aboutme',
    layer: 'public-profile',
    label: 'پروفایل معرفی عمومی',
    name: 'About.me',
    url: 'https://about.me/ghezelbaash',
    role: 'اتصال نام، کلینیک، حوزه فعالیت و وب‌سایت رسمی',
    entity: 'physician',
    evidenceTier: 2,
  },
  {
    id: 'linktree',
    layer: 'official-link-hub',
    label: 'هاب پیوندهای رسمی',
    name: 'Linktree',
    url: 'https://linktr.ee/Doctor.ghezelbaash',
    role: 'تجمیع مسیرهای رسمی شبکه‌های اجتماعی، تماس و وب‌سایت',
    entity: 'physician-clinic',
    evidenceTier: 2,
  },
];

export const nationalAuthoritySignals = {
  local: {
    locationEntity: true,
    googleRatingSnapshot: { ratingValue: 5, bestRating: 5, ratingCount: 163, observedAt: '2026-07-10' },
    phone: '+989308209494',
    address: 'کرمانشاه، میدان ۱۷ شهریور، ساختمان ویستا',
  },
  national: {
    researchPublications: 2,
    publicKnowledgeGraphEntities: 2,
    publicAiDataset: true,
    versionedStructuredDataRepository: true,
    archivedDoiLayer: true,
    externalAuthorityNodes: authorityNetwork.length,
  },
  media: {
    videos: 12,
    chapterTracks: 12,
    portfolioPath: 'https://www.instagram.com/doctor.ghezelbaash/',
  },
};
