export const site = {
  url: "https://www.ghezelbaash.ir/",
  name: "دکتر سعید قزلباش",
  legalName: "دکتر محمدسعید قزلباش",
  givenName: "محمدسعید",
  familyName: "قزلباش",
  latinName: "Dr. Saeed Ghezelbaash",
  clinicName: "کلینیک زیبایی دکتر سعید قزلباش",
  title:
    "دکتر سعید قزلباش | پزشک زیبایی کرمانشاه؛ خدمات، شواهد و تماس",
  articleHeadline:
    "دکتر سعید قزلباش؛ پزشک زیبایی در کرمانشاه، خدمات و معیارهای انتخاب",
  description:
    "صفحه رسمی دکتر سعید قزلباش، پزشک زیبایی در کرمانشاه؛ خدمات جراحی و غیرجراحی، معیار انتخاب درمان، سوابق پژوهشی و کلینیک با ۱۶۳ نظر و امتیاز ۵ در Google Maps.",
  language: "fa-IR",
  direction: "rtl",
  phone: "+989308209494",
  phoneDisplay: "۰۹۳۰ ۸۲۰ ۹۴۹۴",
  email: "doctor@ghezelbaash.ir",
  instagram: "https://www.instagram.com/doctor.ghezelbaash/",
  instagramReels: "https://www.instagram.com/doctor.ghezelbaash/reels/",
  instagramDirect: "https://ig.me/m/doctor.ghezelbaash",
  instagramHandle: "@Doctor.Ghezelbaash",
  facebookProfile: "https://www.facebook.com/Ghezelbaash/",
  pinterestProfile: "https://www.pinterest.com/qezelbaash/",
  maps: "https://www.google.com/maps?cid=12350483144643112463",
  mapsSearch:
    "https://www.google.com/maps/search/?api=1&query=کلینیک%20زیبایی%20دکتر%20قزلباش%20کرمانشاه&query_place_id=ChIJBTOYDOTt-j8RD-7mAPy6Zas",
  googlePlaceId: "ChIJBTOYDOTt-j8RD-7mAPy6Zas",
  googleCid: "12350483144643112463",
  doctorGoogleKnowledgeGraphId: "/g/11nqdfk76c",
  doctorGoogleKnowledgeGraphUrl:
    "https://www.google.com/search?kgmid=/g/11nqdfk76c",
  doctorCloudKnowledgeGraphMid: "C-02KY8SVQ2",
  clinicGoogleLocalKnowledgeGraphId: "/g/11r3rzdtb3",
  clinicGoogleLocalKnowledgeGraphUrl:
    "https://www.google.com/search?kgmid=/g/11r3rzdtb3",
  openStreetMap: "https://www.openstreetmap.org/node/13530287096",
  openStreetMapNode: "13530287096",
  address: "کرمانشاه، میدان ۱۷ شهریور، ساختمان ویستا",
  streetAddress: "میدان ۱۷ شهریور، ساختمان ویستا",
  city: "کرمانشاه",
  region: "کرمانشاه",
  postalCode: "6714657412",
  countryCode: "IR",
  hours: "شنبه تا پنج‌شنبه، ۱۶:۰۰ تا ۲۲:۰۰",
  latitude: 34.3400698,
  longitude: 47.0852334,
  doctorWikidata: "https://www.wikidata.org/entity/Q140287622",
  doctorWikidataId: "Q140287622",
  placeWikidata: "https://www.wikidata.org/entity/Q140288589",
  placeWikidataId: "Q140288589",
  orcid: "0009-0001-9346-8475",
  orcidUrl: "https://orcid.org/0009-0001-9346-8475",
  ncbiBibliography:
    "https://www.ncbi.nlm.nih.gov/myncbi/saeed.ghezelbash.1/bibliography/public/",
  zenodoRecord: "https://doi.org/10.5281/zenodo.18765169",
  githubRepository: "https://github.com/medicaldoctor91/doctor-ghezelbaash",
  githubProfile: "https://github.com/Medicaldoctor91",
  huggingFaceProfile: "https://huggingface.co/Ghezelbaash",
  huggingFaceDataset:
    "https://huggingface.co/datasets/doctor-ghezelbaash/dr-saeid-ghezelbaash-entity-data",
  datasetWikidata: "https://www.wikidata.org/entity/Q140304972",
  datasetWikidataId: "Q140304972",
  linkedinProfile: "https://www.linkedin.com/in/saeed-ghezelbash-93310a96",
  aboutMeProfile: "https://about.me/ghezelbaash",
  linktreeProfile: "https://linktr.ee/Doctor.ghezelbaash",
  xProfile: "https://x.com/Qezelbaash",
  irimc: "167430",
  irimcVerification:
    "https://membersearch.irimc.org/member/profile?id=9efaaf28-52ff-49ad-8d45-be6e48c4fa3e",
  heroImage: "/images/responsive/doctor-portrait-1200.jpg",
  logo: "/assets/brand/doctor-hand-syringe-logo-512.png",
  ogImage: "/og/home.jpg",
  datePublished: "2026-07-10T12:00:00+03:30",
  dateModified: "2026-07-14T16:30:00+03:30",
  liveSourceOfTruth: "https://www.ghezelbaash.ir/",
  sourceTruthObservedAt: "2026-07-14",
  googleBusinessProfile: {
    ratingValue: 5,
    bestRating: 5,
    ratingCount: 163,
    observedAt: "2026-07-14",
    sourceName: "Google Maps",
    sourceUrl: "https://www.google.com/maps?cid=12350483144643112463",
    evidenceStatus: "first-party-live-site-and-external-map-dated-snapshot",
  },
  externalProfiles: [
    {
      id: "instagram",
      name: "صفحه رسمی اینستاگرام دکتر سعید قزلباش",
      url: "https://www.instagram.com/doctor.ghezelbaash/",
      publisher: "Instagram",
      evidenceType: "owned-external-social-profile",
      evidenceTier: 2,
    },
    {
      id: "irimc",
      name: "پروفایل رسمی دکتر محمدسعید قزلباش در سازمان نظام پزشکی",
      url: "https://membersearch.irimc.org/member/profile?id=9efaaf28-52ff-49ad-8d45-be6e48c4fa3e",
      publisher: "سازمان نظام پزشکی جمهوری اسلامی ایران",
      evidenceType: "official-registration",
      evidenceTier: 1,
    },
    {
      id: "orcid",
      name: "شناسه پژوهشگر دکتر سعید قزلباش در ORCID",
      url: "https://orcid.org/0009-0001-9346-8475",
      publisher: "ORCID",
      evidenceType: "persistent-researcher-identifier",
      evidenceTier: 1,
    },
    {
      id: "drdr",
      name: "پروفایل دکتر سعید قزلباش در دکتردکتر",
      url: "https://drdr.ir/dr/92014/%D8%AF%DA%A9%D8%AA%D8%B1-%D8%B3%D8%B9%DB%8C%D8%AF-%D9%82%D8%B2%D9%84%D8%A8%D8%A7%D8%B4/",
      publisher: "دکتردکتر",
      evidenceType: "third-party-profile",
      evidenceTier: 3,
    },
    {
      id: "doctor-yab",
      name: "پروفایل دکتر سعید قزلباش در دکتریاب",
      url: "https://doctor-yab.ir/Search/43609/%D8%AF%DA%A9%D8%AA%D8%B1-%D8%B3%D8%B9%DB%8C%D8%AF-%D9%82%D8%B2%D9%84%D8%A8%D8%A7%D8%B4/",
      publisher: "دکتریاب",
      evidenceType: "third-party-profile",
      evidenceTier: 3,
    },
    {
      id: "nobat19",
      name: "پروفایل دکتر سعید قزلباش در نوبت ۱۹",
      url: "https://nobat19.com/823/",
      publisher: "نوبت ۱۹",
      evidenceType: "third-party-profile",
      evidenceTier: 3,
    },
    {
      id: "huggingface-profile",
      name: "پروفایل عمومی دکتر سعید قزلباش در Hugging Face",
      url: "https://huggingface.co/Ghezelbaash",
      publisher: "Hugging Face",
      evidenceType: "owned-external-ai-profile",
      evidenceTier: 2,
    },
    {
      id: "linkedin",
      name: "پروفایل حرفه‌ای دکتر سعید قزلباش در LinkedIn",
      url: "https://www.linkedin.com/in/saeed-ghezelbash-93310a96",
      publisher: "LinkedIn",
      evidenceType: "owned-external-professional-profile",
      evidenceTier: 2,
    },
    {
      id: "aboutme",
      name: "پروفایل معرفی دکتر سعید قزلباش در About.me",
      url: "https://about.me/ghezelbaash",
      publisher: "About.me",
      evidenceType: "owned-external-profile",
      evidenceTier: 2,
    },
    {
      id: "linktree",
      name: "هاب پیوندهای رسمی دکتر سعید قزلباش در Linktree",
      url: "https://linktr.ee/Doctor.ghezelbaash",
      publisher: "Linktree",
      evidenceType: "owned-external-link-hub",
      evidenceTier: 2,
    },
  ],
  researchProfiles: [
    {
      id: "research-bipolar-omega3",
      name: "Effects of Omega-3 Supplement in the Treatment of Patients with Bipolar I Disorder",
      url: "https://pubmed.ncbi.nlm.nih.gov/27280013/",
      fullTextUrl: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4882968/",
      doiUrl: "https://doi.org/10.4103/2008-7802.182734",
      doi: "10.4103/2008-7802.182734",
      pmid: "27280013",
      pmcid: "PMC4882968",
      datePublished: "2016",
      journal: "Journal of Research in Medical Sciences",
      publisher: "PubMed / PubMed Central",
    },
    {
      id: "research-mdd-attachment",
      name: "Individuals with Major Depressive Disorder Report High Scores of Insecure-Avoidant and Insecure-Anxious Attachment Styles, Dissociative Identity Symptoms, and Adult Traumatic Events",
      url: "https://pubmed.ncbi.nlm.nih.gov/34574943/",
      alternateUrl: "https://www.mdpi.com/2227-9032/9/9/1169",
      doiUrl: "https://doi.org/10.3390/healthcare9091169",
      doi: "10.3390/healthcare9091169",
      pmid: "34574943",
      datePublished: "2021-09-06T00:00:00Z",
      journal: "Healthcare",
      publisher: "MDPI / PubMed",
    },
  ],
} as const;
