export const homepageSubsectionAnchorRegistry: Record<string, string> = {
  'انتخاب درمان خطوط صورت و چین‌های حرکتی': 'facial-lines-treatment-selection',
  'انتخاب درمان کاهش حجم و تغییر حمایت صورت': 'facial-volume-loss-treatment-selection',
  'انتخاب درمان گودی، پف و تیرگی زیر چشم': 'under-eye-treatment-selection',
  'انتخاب درمان افتادگی صورت': 'facial-sagging-treatment-selection',
  'انتخاب درمان جای جوش و اسکار آکنه': 'acne-scar-treatment-selection',
  'انتخاب درمان غبغب و برجستگی زیر چانه': 'submental-fullness-treatment-selection',
  'انتخاب درمان ریزش مو': 'hair-loss-treatment-selection',
  'انتخاب درمان ترکیبی و مرحله‌بندی مداخلات': 'combined-aesthetic-treatment-selection',
  'بوتاکس و بوتولینوم توکسین': 'botulinum-toxin-guide',
  'راهنمای فیلر و انتخاب ماده تزریقی': 'dermal-filler-guide',
  'فیلر لب؛ فرم، حرکت و نسبت‌های صورت': 'lip-filler-guide',
  'فیلر زیر چشم؛ گودی، پف و میدفیس': 'under-eye-filler-guide',
  'تزریق برای کانتور صورت، چانه، فک، گونه و بینی': 'facial-contouring-injections',
  'اصلاح فیلر و هیالورونیداز': 'filler-correction-hyaluronidase',
  'راهنمای لیفت نخ': 'thread-lift-guide',
  'ارزیابی افتادگی صورت و کاندید مناسب': 'facial-sagging-assessment',
  'پیری میدفیس، ابرو و خط فک': 'midface-and-jawline-aging',
  'مقایسه لیفت غیرجراحی با جراحی': 'non-surgical-versus-surgical-lift',
  'کنترل آکنه فعال پیش از درمان اسکار': 'active-acne-before-scar-treatment',
  'انواع اسکار آکنه و نقشه انتخاب ابزار': 'acne-scar-types',
  'سابسیژن؛ آزادسازی چسبندگی اسکار': 'subcision-guide',
  'TCA CROSS، میکرونیدلینگ، RF و لیزر': 'tca-cross-microneedling',
  'لک، ملاسما و تیرگی پس از التهاب': 'pigmentation-melasma-guide',
  'اسکین‌بوستر، مزوژل و درمان کیفیت پوست': 'skin-booster-mesogel',
  'PRP برای جوان‌سازی پوست': 'prp-skin-rejuvenation',
  'تشخیص ریزش مو و بررسی پوست سر': 'hair-loss-diagnosis',
  'PRP مو؛ نقش، کاندید و محدودیت': 'hair-prp-guide',
  'مزوتراپی مو و ترکیبات تزریقی': 'hair-mesotherapy-guide',
  'کاشت مو و زمان ارجاع': 'hair-transplant-referral',
  'ارزیابی چربی زیر چانه و علت غبغب': 'submental-fat-assessment',
  'ساکشن غبغب؛ کاندید، توان و عارضه': 'submental-liposuction-guide',
  'کانتور چانه و خط فک': 'jawline-chin-contouring',
  'ارزیابی کانتورینگ بدن و لاغری موضعی': 'body-contouring-evaluation',
  'ارزیابی بلفاروپلاستی و جراحی پلک': 'blepharoplasty-evaluation',
  'ارزیابی رینوپلاستی و جراحی بینی': 'rhinoplasty-evaluation',
  'ارزیابی لیفت جراحی صورت و گردن': 'facelift-necklift-evaluation',
  'ارزیابی جراحی فک و مشکلات اسکلتی': 'orthognathic-surgery-evaluation',
  'ارزیابی جراحی کاشت مو': 'hair-transplant-surgical-evaluation',
  'چه زمانی جراحی زیبایی لازم یا منطقی‌تر است؟': 'when-aesthetic-surgery-is-necessary',
  'ارزیابی درمان زیبایی ناموفق یا نتیجه نامطلوب': 'failed-aesthetic-treatment-assessment',
  'عوارض فیلر و زمان بررسی فوری': 'filler-complications',
  'عوارض بوتاکس و اختلال عملکرد': 'botox-complications',
  'عوارض لیفت نخ': 'thread-lift-complications',
  'عوارض درمان‌های پوستی و اسکار': 'skin-treatment-complications',
  'علائم خطر بعد از درمان زیبایی': 'aesthetic-emergency-warning-signs',
  'عوامل تعیین‌کننده هزینه درمان زیبایی': 'aesthetic-treatment-cost-factors',
  'مشاوره اولیه رایگان شامل چه چیزی است؟': 'free-aesthetic-consultation',
  'آمادگی پیش از مشاوره': 'pre-consultation-preparation',
  'برنامه درمان و پیگیری': 'treatment-planning-and-follow-up',
  'پرسش‌های انتخاب پزشک و روش': 'faq-doctor-selection',
  'پرسش‌های انتخاب درمان': 'faq-treatment-selection',
  'پرسش‌های ایمنی و کاندید مناسب': 'faq-safety-and-candidacy',
  'پرسش‌های هزینه و زمان‌بندی': 'faq-cost-and-timing',
  'پرسش‌های اصلاح درمان': 'faq-treatment-revision',
  'پرسش‌های کلینیک و نوبت': 'faq-clinic-and-appointment',
  'پژوهش پزشکی': 'medical-research',
  'آموزش پزشکی': 'medical-education',
};
