export const galleryImages = [
  {
    id: 'doctor-portrait',
    base: 'doctor-portrait',
    alt: 'دکتر سعید قزلباش، پزشک زیبایی در کرمانشاه',
    caption: 'دکتر محمدسعید قزلباش؛ شماره نظام پزشکی ۱۶۷۴۳۰',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
    eager: true,
  },
  {
    id: 'doctor-exam',
    base: 'doctor-exam',
    alt: 'ارزیابی پزشکی چهره پیش از انتخاب درمان زیبایی',
    caption: 'بررسی چهره و حرکت صورت پیش از انتخاب درمان',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
  },
  {
    id: 'doctor-with-staff',
    base: 'doctor-with-staff',
    alt: 'دکتر سعید قزلباش همراه با تیم کلینیک زیبایی در کرمانشاه',
    caption: 'دکتر سعید قزلباش و تیم کلینیک',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
  },
  {
    id: 'clinic-interior',
    base: 'clinic-interior',
    alt: 'فضای داخلی کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'فضای داخلی کلینیک در ساختمان ویستا، میدان ۱۷ شهریور کرمانشاه',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-waiting-room',
    base: 'clinic-waiting-room',
    alt: 'فضای انتظار کلینیک زیبایی دکتر سعید قزلباش',
    caption: 'فضای انتظار کلینیک',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-corridor',
    base: 'clinic-corridor',
    alt: 'راهروی کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'راهروی کلینیک',
    width: 768,
    height: 1365,
    widths: [480, 768],
  },
  {
    id: 'clinic-interior-2',
    base: 'clinic-interior-2',
    alt: 'نمای دیگری از فضای داخلی کلینیک زیبایی دکتر سعید قزلباش',
    caption: 'یکی از فضاهای داخلی کلینیک',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-environment-3',
    base: 'clinic-environment-3',
    alt: 'محیط کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'نمای دیگری از محیط کلینیک',
    width: 768,
    height: 1365,
    widths: [480, 768],
  },
];

export const videos = [
  {
    id: 'home-workshop-thread-lift-training',
    file: 'thread-lift-training-workshop-dr-ghezelbash.mp4',
    title: 'چه کسی برای لیفت نخ مناسب است؟',
    description: 'بخشی از یک کارگاه آموزشی درباره انتخاب فرد مناسب، وضعیت پوست و محدودیت‌های واقعی لیفت با نخ.',
    thumbnail: '/videos/thumbnails/thread-lift-training-workshop-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT30.604S', durationSeconds: 31, exactDurationSeconds: 30.604,
    relatedHeadingIncludes: 'نخ، لیفت بدون جراحی',
    tags: ['لیفت نخ', 'آموزش پزشکان', 'انتخاب کاندید'],
    chapterTrack: '/videos/chapters/thread-lift-training-workshop-dr-ghezelbash.vtt',
  },
  {
    id: 'home-workshop-thread-lift-advanced',
    file: 'thread-lift-workshop-trin-dr-ghezelbash.mp4',
    title: 'ارزیابی چهره پیش از لیفت نخ',
    description: 'نمونه‌ای از آموزش پزشکی درباره بررسی افتادگی، انتخاب جهت کشش و زمانی که نخ گزینه مناسبی نیست.',
    thumbnail: '/videos/thumbnails/thread-lift-workshop-trin-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT38.917S', durationSeconds: 39, exactDurationSeconds: 38.917,
    relatedHeadingIncludes: 'نخ، لیفت بدون جراحی',
    tags: ['لیفت نخ', 'آناتومی صورت', 'آموزش پزشکی'],
    chapterTrack: '/videos/chapters/thread-lift-workshop-trin-dr-ghezelbash.vtt',
  },
  {
    id: 'clinic-patient-experience-review',
    file: 'patient-satisfaction-review-dr-saeed-ghezelbash.mp4',
    title: 'تجربه یکی از مراجعه‌کنندگان کلینیک',
    description: 'روایتی کوتاه از تجربه مراجعه و ارتباط با کلینیک دکتر سعید قزلباش در کرمانشاه.',
    thumbnail: '/videos/thumbnails/patient-satisfaction-review-dr-saeed-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT20.133S', durationSeconds: 21, exactDurationSeconds: 20.133,
    relatedHeadingIncludes: 'عکس مدل، شرح حال نیست',
    tags: ['کلینیک', 'کرمانشاه', 'تجربه مراجعه'],
    chapterTrack: '/videos/chapters/patient-satisfaction-review-dr-saeed-ghezelbash.vtt',
  },
  {
    id: 'botox-vs-subcision-dynamic-static-scar',
    file: 'botox-vs-subcision-scars-explaining-dr-ghezelbash.mp4',
    title: 'بوتاکس یا سابسیژن؛ تفاوت چین حرکتی و اسکار',
    description: 'توضیح تفاوت چین وابسته به حرکت عضلات با اسکار و چسبندگی بافتی که به درمان دیگری نیاز دارد.',
    thumbnail: '/videos/thumbnails/botox-vs-subcision-scars-explaining-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT56.077S', durationSeconds: 57, exactDurationSeconds: 56.077,
    relatedHeadingIncludes: 'هر چروکی بوتاکس می‌خواهد',
    tags: ['بوتاکس', 'سابسیژن', 'چین دینامیک', 'اسکار'],
    chapterTrack: '/videos/chapters/botox-vs-subcision-scars-explaining-dr-ghezelbash.vtt',
  },
  {
    id: 'filler-under-eye-transformation',
    file: 'under-eye-filler-transformation-dr-saeed-ghezelbash.mp4',
    title: 'چه زمانی فیلر زیر چشم مناسب است؟',
    description: 'مروری کوتاه بر تفاوت گودی واقعی با پف، تیرگی و سایه بخش میانی صورت پیش از تزریق فیلر.',
    thumbnail: '/videos/thumbnails/under-eye-filler-transformation-dr-saeed-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT8.496S', durationSeconds: 9, exactDurationSeconds: 8.496,
    relatedHeadingIncludes: 'فیلر صورت را لیفت می‌کند',
    tags: ['فیلر زیر چشم', 'گودی زیر چشم', 'میدفیس'],
    chapterTrack: '/videos/chapters/under-eye-filler-transformation-dr-saeed-ghezelbash.vtt',
  },
  {
    id: 'filler-under-eye-before-after',
    file: 'under-eye-filler-before-after-dr-ghezelbash.mp4',
    title: 'نمونه قبل و بعد فیلر زیر چشم',
    description: 'یک نمونه کوتاه از نتیجه درمان؛ نتیجه هر فرد به شرایط چهره، پوست و ارزیابی پزشکی وابسته است.',
    thumbnail: '/videos/thumbnails/under-eye-filler-before-after-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT8.467S', durationSeconds: 9, exactDurationSeconds: 8.467,
    relatedHeadingIncludes: 'فیلر صورت را لیفت می‌کند',
    tags: ['فیلر زیر چشم', 'قبل و بعد', 'پزشکی زیبایی'],
    chapterTrack: '/videos/chapters/under-eye-filler-before-after-dr-ghezelbash.vtt',
  },
  {
    id: 'cat-eye-thread-lift-before-after',
    file: 'cat-eye-thread-lift-before-after-dr-ghezelbash.mp4',
    title: 'نمونه نتیجه لیفت نخ ابرو',
    description: 'نمونه‌ای کوتاه از تغییر ابرو و اطراف چشم؛ نتیجه به فرم صورت و انتخاب فرد مناسب وابسته است.',
    thumbnail: '/videos/thumbnails/cat-eye-thread-lift-before-after-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT5.988S', durationSeconds: 6, exactDurationSeconds: 5.988,
    relatedHeadingIncludes: 'نخ، لیفت بدون جراحی',
    tags: ['لیفت نخ ابرو', 'چشم گربه‌ای', 'قبل و بعد'],
    chapterTrack: '/videos/chapters/cat-eye-thread-lift-before-after-dr-ghezelbash.vtt',
  },
  {
    id: 'jalupro-vs-profhilo-skin-boosters',
    file: 'jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.mp4',
    title: 'تفاوت جالپرو، پروفایلو و اسکین‌بوسترها',
    description: 'مقایسه این محصولات بر اساس نیاز پوست و تفاوت کاربرد آن‌ها با فیلرهای حجم‌دهنده.',
    thumbnail: '/videos/thumbnails/jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT62.458S', durationSeconds: 63, exactDurationSeconds: 62.458,
    relatedHeadingIncludes: 'جوانسازی یعنی تزریق بیشتر',
    tags: ['جالپرو', 'پروفایلو', 'اسکین‌بوستر', 'جوانسازی پوست'],
    chapterTrack: '/videos/chapters/jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.vtt',
  },
  {
    id: 'nonsurgical-rhinoplasty-boundary',
    file: 'nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.mp4',
    title: 'فیلر بینی چه کاری می‌تواند انجام دهد؟',
    description: 'نمونه‌ای کوتاه از اصلاح ظاهری با فیلر و توضیح اینکه فیلر بینی را کوچک یا مشکل تنفسی را درمان نمی‌کند.',
    thumbnail: '/videos/thumbnails/nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT7.381S', durationSeconds: 8, exactDurationSeconds: 7.381,
    relatedHeadingIncludes: 'غیرجراحی بهتر است',
    tags: ['فیلر بینی', 'رینوپلاستی', 'مرز ارجاع'],
    chapterTrack: '/videos/chapters/nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.vtt',
  },
  {
    id: 'nose-filler-before-after',
    file: 'nose-filler-before-after-results-dr-ghezelbash.mp4',
    title: 'نمونه قبل و بعد فیلر بینی',
    description: 'یک نمونه کوتاه از نتیجه ظاهری؛ ارزیابی ساختار بینی و ریسک عروقی همچنان ضروری است.',
    thumbnail: '/videos/thumbnails/nose-filler-before-after-results-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT7.706S', durationSeconds: 8, exactDurationSeconds: 7.706,
    relatedHeadingIncludes: 'فیلر صورت را لیفت می‌کند',
    tags: ['فیلر بینی', 'قبل و بعد', 'ریسک عروقی'],
    chapterTrack: '/videos/chapters/nose-filler-before-after-results-dr-ghezelbash.vtt',
  },
  {
    id: 'proper-subcision-technique-guide',
    file: 'proper-subcision-technique-guide-dr-ghezelbash.mp4',
    title: 'سابسیژن برای کدام جای جوش مناسب است؟',
    description: 'توضیح نقش سابسیژن در آزادکردن اسکارهای چسبنده و تفاوت آن با درمان لک یا اسکارهای دیگر.',
    thumbnail: '/videos/thumbnails/proper-subcision-technique-guide-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT35.792S', durationSeconds: 36, exactDurationSeconds: 35.792,
    relatedHeadingIncludes: 'جای جوش» یک بیماری واحد نیست',
    tags: ['سابسیژن', 'اسکار آکنه', 'جای جوش'],
    chapterTrack: '/videos/chapters/proper-subcision-technique-guide-dr-ghezelbash.vtt',
  },
  {
    id: 'mesoneedling-dark-spots-warning',
    file: 'why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.mp4',
    title: 'چرا مزونیدلینگ می‌تواند لک را بدتر کند؟',
    description: 'توضیح تفاوت لک و التهاب و اینکه تحریک نامناسب پوست ممکن است تیرگی پس از التهاب را بیشتر کند.',
    thumbnail: '/videos/thumbnails/why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT48.208S', durationSeconds: 49, exactDurationSeconds: 48.208,
    relatedHeadingIncludes: 'پوستم را جوان کن',
    tags: ['مزونیدلینگ', 'لک', 'PIH', 'ایمنی پوست'],
    chapterTrack: '/videos/chapters/why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.vtt',
  },
];
