export const galleryImages = [
  {
    id: 'doctor-portrait',
    base: 'doctor-portrait',
    alt: 'دکتر سعید قزلباش، پزشک زیبایی در کرمانشاه',
    caption: 'دکتر محمدسعید قزلباش؛ شماره نظام پزشکی ۱۶۷۴۳۰',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
    eager: true,
  },
  {
    id: 'doctor-exam',
    base: 'doctor-exam',
    alt: 'ارزیابی پزشکی چهره پیش از انتخاب درمان زیبایی',
    caption: 'ارزیابی چهره، حرکت و لایهٔ ساختاری پیش از مداخله',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
  },
  {
    id: 'doctor-with-staff',
    base: 'doctor-with-staff',
    alt: 'دکتر سعید قزلباش همراه با تیم کلینیک زیبایی در کرمانشاه',
    caption: 'پزشک و تیم کلینیک زیبایی دکتر سعید قزلباش',
    width: 1600,
    height: 1067,
    widths: [480, 768, 1200, 1600],
  },
  {
    id: 'clinic-interior',
    base: 'clinic-interior',
    alt: 'فضای داخلی کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'فضای داخلی کلینیک در ساختمان ویستا، میدان ۱۷ شهریور کرمانشاه',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-waiting-room',
    base: 'clinic-waiting-room',
    alt: 'فضای انتظار کلینیک زیبایی دکتر سعید قزلباش',
    caption: 'فضای انتظار کلینیک',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-corridor',
    base: 'clinic-corridor',
    alt: 'راهروی کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'محیط کلینیک زیبایی دکتر سعید قزلباش',
    width: 768,
    height: 1365,
    widths: [480, 768],
  },
  {
    id: 'clinic-interior-2',
    base: 'clinic-interior-2',
    alt: 'نمای دیگری از فضای داخلی کلینیک زیبایی دکتر سعید قزلباش',
    caption: 'فضای بالینی و مراجعه در کلینیک',
    width: 768,
    height: 1024,
    widths: [480, 768],
  },
  {
    id: 'clinic-environment-3',
    base: 'clinic-environment-3',
    alt: 'محیط کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه',
    caption: 'نمای محیط کلینیک',
    width: 768,
    height: 1365,
    widths: [480, 768],
  },
];

export const videos = [
  {
    id: 'home-workshop-thread-lift-training',
    file: 'thread-lift-training-workshop-dr-ghezelbash.mp4',
    title: 'ورکشاپ آموزشی لیفت نخ؛ انتخاب کاندید',
    description: 'بخشی از ورکشاپ آموزشی با تمرکز بر آناتومی صورت، انتخاب بیمار و تصمیم‌گیری پیش از اجرای تکنیک.',
    thumbnail: '/videos/thumbnails/thread-lift-training-workshop-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT30.604S', durationSeconds: 31, exactDurationSeconds: 30.604,
    sectionId: 'medical-research-and-education',
    subsectionId: 'medical-education',
    tags: ['لیفت نخ', 'آموزش پزشکان', 'انتخاب کاندید'],
    chapterTrack: '/videos/chapters/thread-lift-training-workshop-dr-ghezelbash.vtt',
  },
  {
    id: 'home-workshop-thread-lift-advanced',
    file: 'thread-lift-workshop-trin-dr-ghezelbash.mp4',
    title: 'ورکشاپ پیشرفته لیفت نخ و ارزیابی چهره',
    description: 'نمونه‌ای از فضای آموزش پیشرفته درباره ارزیابی چهره، بردار کشش و مرز توان لیفت نخ.',
    thumbnail: '/videos/thumbnails/thread-lift-workshop-trin-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT38.917S', durationSeconds: 39, exactDurationSeconds: 38.917,
    sectionId: 'medical-research-and-education',
    subsectionId: 'medical-education',
    tags: ['لیفت نخ', 'آناتومی صورت', 'آموزش پزشکی'],
    chapterTrack: '/videos/chapters/thread-lift-workshop-trin-dr-ghezelbash.vtt',
  },
  {
    id: 'clinic-patient-experience-review',
    file: 'patient-satisfaction-review-dr-saeed-ghezelbash.mp4',
    title: 'رضایت زیباجو از خدمات زیبایی دکتر سعید قزلباش',
    description: 'روایت کوتاهی از تجربه مراجعه و ارتباط با کلینیک دکتر سعید قزلباش در کرمانشاه.',
    thumbnail: '/videos/thumbnails/patient-satisfaction-review-dr-saeed-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT20.133S', durationSeconds: 21, exactDurationSeconds: 20.133,
    sectionId: 'clinic-information-kermanshah',
    subsectionId: null,
    tags: ['کلینیک', 'کرمانشاه', 'تجربه مراجعه'],
    chapterTrack: '/videos/chapters/patient-satisfaction-review-dr-saeed-ghezelbash.vtt',
  },
  {
    id: 'botox-vs-subcision-dynamic-static-scar',
    file: 'botox-vs-subcision-scars-explaining-dr-ghezelbash.mp4',
    title: 'تفاوت بوتاکس، چین دینامیک و سابسیژن',
    description: 'توضیح تفاوت میان چین وابسته به حرکت عضله و اسکار یا چسبندگی بافتی که مسیر درمان متفاوتی دارد.',
    thumbnail: '/videos/thumbnails/botox-vs-subcision-scars-explaining-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT56.077S', durationSeconds: 57, exactDurationSeconds: 56.077,
    sectionId: 'injectable-aesthetic-treatments',
    subsectionId: 'botulinum-toxin-guide',
    tags: ['بوتاکس', 'سابسیژن', 'چین دینامیک', 'اسکار'],
    chapterTrack: '/videos/chapters/botox-vs-subcision-scars-explaining-dr-ghezelbash.vtt',
  },
  {
    id: 'filler-under-eye-transformation',
    file: 'under-eye-filler-transformation-dr-saeed-ghezelbash.mp4',
    title: 'ارزیابی فیلر زیر چشم',
    description: 'مروری کوتاه بر ارزیابی گودی، سایه، پف و افت میدفیس پیش از تصمیم‌گیری برای فیلر زیر چشم.',
    thumbnail: '/videos/thumbnails/under-eye-filler-transformation-dr-saeed-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT8.496S', durationSeconds: 9, exactDurationSeconds: 8.496,
    sectionId: 'injectable-aesthetic-treatments',
    subsectionId: 'under-eye-filler-guide',
    tags: ['فیلر زیر چشم', 'گودی زیر چشم', 'میدفیس'],
    chapterTrack: '/videos/chapters/under-eye-filler-transformation-dr-saeed-ghezelbash.vtt',
  },
  {
    id: 'filler-under-eye-before-after',
    file: 'under-eye-filler-before-after-dr-ghezelbash.mp4',
    title: 'قبل و بعد فیلر زیر چشم',
    description: 'نمونه کوتاه قبل و بعد؛ نتیجه هر فرد به شرایط چهره، کیفیت پوست و ارزیابی پزشکی وابسته است.',
    thumbnail: '/videos/thumbnails/under-eye-filler-before-after-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT8.467S', durationSeconds: 9, exactDurationSeconds: 8.467,
    sectionId: 'injectable-aesthetic-treatments',
    subsectionId: 'under-eye-filler-guide',
    tags: ['فیلر زیر چشم', 'قبل و بعد', 'پزشکی زیبایی'],
    chapterTrack: '/videos/chapters/under-eye-filler-before-after-dr-ghezelbash.vtt',
  },
  {
    id: 'cat-eye-thread-lift-before-after',
    file: 'cat-eye-thread-lift-before-after-dr-ghezelbash.mp4',
    title: 'قبل و بعد لیفت نخ ابرو و چشم',
    description: 'نمونه کوتاه از تغییر انتخابی ابرو و ناحیه چشم با تأکید بر وابستگی نتیجه به آناتومی و انتخاب کاندید.',
    thumbnail: '/videos/thumbnails/cat-eye-thread-lift-before-after-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT5.988S', durationSeconds: 6, exactDurationSeconds: 5.988,
    sectionId: 'lifting-and-facial-aging',
    subsectionId: 'thread-lift-guide',
    tags: ['لیفت نخ ابرو', 'چشم گربه‌ای', 'قبل و بعد'],
    chapterTrack: '/videos/chapters/cat-eye-thread-lift-before-after-dr-ghezelbash.vtt',
  },
  {
    id: 'jalupro-vs-profhilo-skin-boosters',
    file: 'jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.mp4',
    title: 'مقایسه جالپرو، پروفایلو و اسکین‌بوسترها',
    description: 'مقایسه اسکین‌بوسترها بر اساس نیاز پوست، مکانیسم و مرز آن‌ها با فیلر کلاسیک.',
    thumbnail: '/videos/thumbnails/jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT62.458S', durationSeconds: 63, exactDurationSeconds: 62.458,
    sectionId: 'skin-scar-rejuvenation',
    subsectionId: 'skin-booster-mesogel',
    tags: ['جالپرو', 'پروفایلو', 'اسکین‌بوستر', 'جوانسازی پوست'],
    chapterTrack: '/videos/chapters/jalupro-vs-profhilo-skin-boosters-compared-dr-ghezelbash.vtt',
  },
  {
    id: 'nonsurgical-rhinoplasty-boundary',
    file: 'nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.mp4',
    title: 'مرز فیلر بینی و رینوپلاستی',
    description: 'نمونه کوتاه از اصلاح ظاهری انتخابی با فیلر و یادآوری اینکه فیلر بینی را کوچک یا مشکل تنفسی را درمان نمی‌کند.',
    thumbnail: '/videos/thumbnails/nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT7.381S', durationSeconds: 8, exactDurationSeconds: 7.381,
    sectionId: 'aesthetic-surgery-and-referral',
    subsectionId: 'rhinoplasty-evaluation',
    tags: ['فیلر بینی', 'رینوپلاستی', 'مرز ارجاع'],
    chapterTrack: '/videos/chapters/nonsurgical-rhinoplasty-before-after-result-dr-ghezelbash.vtt',
  },
  {
    id: 'nose-filler-before-after',
    file: 'nose-filler-before-after-results-dr-ghezelbash.mp4',
    title: 'قبل و بعد فیلر بینی',
    description: 'نمونه کوتاه قبل و بعد فیلر بینی؛ نتیجه ظاهری جایگزین ارزیابی ساختار، ریسک عروقی یا جراحی بینی نیست.',
    thumbnail: '/videos/thumbnails/nose-filler-before-after-results-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT7.706S', durationSeconds: 8, exactDurationSeconds: 7.706,
    sectionId: 'injectable-aesthetic-treatments',
    subsectionId: 'facial-contouring-injections',
    tags: ['فیلر بینی', 'قبل و بعد', 'ریسک عروقی'],
    chapterTrack: '/videos/chapters/nose-filler-before-after-results-dr-ghezelbash.vtt',
  },
  {
    id: 'proper-subcision-technique-guide',
    file: 'proper-subcision-technique-guide-dr-ghezelbash.mp4',
    title: 'منطق انتخاب و اجرای سابسیژن',
    description: 'توضیح منطق آزادسازی چسبندگی در اسکارهای منتخب و مرز سابسیژن با درمان رنگ یا اسکارهای غیرچسبنده.',
    thumbnail: '/videos/thumbnails/proper-subcision-technique-guide-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT35.792S', durationSeconds: 36, exactDurationSeconds: 35.792,
    sectionId: 'skin-scar-rejuvenation',
    subsectionId: 'subcision-guide',
    tags: ['سابسیژن', 'اسکار آکنه', 'جای جوش'],
    chapterTrack: '/videos/chapters/proper-subcision-technique-guide-dr-ghezelbash.vtt',
  },
  {
    id: 'mesoneedling-dark-spots-warning',
    file: 'why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.mp4',
    title: 'چرا مزونیدلینگ می‌تواند لک را بدتر کند؟',
    description: 'تفکیک لک و التهاب و توضیح اینکه تحریک نامتناسب پوست می‌تواند خطر تیرگی پس از التهاب را افزایش دهد.',
    thumbnail: '/videos/thumbnails/why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.jpg',
    width: 720, height: 1280, duration: 'PT48.208S', durationSeconds: 49, exactDurationSeconds: 48.208,
    sectionId: 'skin-scar-rejuvenation',
    subsectionId: 'pigmentation-melasma-guide',
    tags: ['مزونیدلینگ', 'لک', 'PIH', 'ایمنی پوست'],
    chapterTrack: '/videos/chapters/why-mesoneedling-makes-dark-spots-worse-dr-ghezelbash.vtt',
  },
];
