import { readFile, writeFile } from 'node:fs/promises';
const release=JSON.parse(await readFile('src/data/release.json','utf8'));
const lock=JSON.parse(await readFile('src/data/semantic/rdf-lock.json','utf8'));
const inv=JSON.parse(await readFile('src/data/release-invariants.json','utf8'));
if(release.release!=='1.1.0'||lock.release!=='1.1.0'||inv.release!=='1.1.0') throw new Error('RDF invariant lock requires fully migrated v1.1.0 source state');
if(!Number.isInteger(lock.triples)||lock.triples<=0) throw new Error('Generated RDF lock has invalid triple count');
if(!/^[0-9a-f]{64}$/.test(lock.jsonldSha256)||!/^[0-9a-f]{64}$/.test(lock.ttlSha256)) throw new Error('Generated RDF lock hashes invalid');
inv.externalRdfTripleCount=lock.triples;
await writeFile('src/data/release-invariants.json',JSON.stringify(inv,null,2)+'\n');
console.log(JSON.stringify({release:release.release,externalRdfTripleCount:lock.triples,jsonldSha256:lock.jsonldSha256,ttlSha256:lock.ttlSha256,integrity:'PASS'},null,2));
