import path from 'node:path';
import { createHash } from 'node:crypto';
import { readFile, access, readdir } from 'node:fs/promises';
import { assembleCanonicalContent } from './lib/assemble-content.mjs';
import { assertDocumentContract, inspectHtml, attr, classes, nearest } from './lib/html-contract.mjs';
const root=process.cwd(),data=path.join(root,'src/data');
const inv=JSON.parse(await readFile(path.join(data,'release-invariants.json'),'utf8'));
const release=JSON.parse(await readFile(path.join(data,'release.json'),'utf8'));
const fail=m=>{throw new Error(m)};
const sha=x=>createHash('sha256').update(x).digest('hex');
async function walk(d){let out=[];for(const e of await readdir(d,{withFileTypes:true})){const p=path.join(d,e.name);e.isDirectory()?out.push(...await walk(p)):out.push(p)}return out;}
const required=['src/content/home.md','src/content-source/000-frontmatter.md','src/layouts/BaseLayout.astro','src/components/DocumentHead.astro','src/components/FloatingActionDock.astro','src/components/GuideNavigator.astro','src/data/semantic/knowledge-graph.jsonld','src/data/semantic/knowledge-graph.ttl','src/data/semantic/rdf-lock.json','src/data/semantic/head-ids.json','src/data/semantic/head-profile.json','src/data/semantic/support-ids.json','src/data/semantic/support-profile.json','src/data/semantic/shapes.ttl','src/data/evidence-registry.json','src/data/evidence-snapshot.json','src/data/volatile-facts.json','src/data/projections/provenance.jsonld','src/styles/global.css','scripts/generate-projections.mjs','scripts/generate-rdf.py','scripts/finalize-dist.mjs','scripts/configure-cloudflare-edge.py','scripts/validate-dist.mjs','src/data/render-calibration.json'];
for(const f of required) await access(path.join(root,f));
await access(path.join(root,'src/styles/critical-mobile.css'));
const graphText=await readFile(path.join(data,'semantic/knowledge-graph.jsonld'),'utf8'),graph=JSON.parse(graphText),content=await readFile(path.join(root,'src/content/home.md'),'utf8'),pkg=JSON.parse(await readFile(path.join(root,'package.json'),'utf8')),robots=await readFile(path.join(root,'public/robots.txt'),'utf8'),llms=await readFile(path.join(data,'projections/llms.txt'),'utf8'),markdown=await readFile(path.join(data,'projections/index.md'),'utf8'),llmsFull=await readFile(path.join(data,'projections/llms-full.txt'),'utf8'),headersTemplate=await readFile(path.join(data,'templates/headers.template'),'utf8'),css=await readFile(path.join(root,'src/styles/global.css'),'utf8'),guide=await readFile(path.join(root,'src/components/GuideNavigator.astro'),'utf8'),headRaw=await readFile(path.join(data,'semantic/head-graph.json'),'utf8'),head=JSON.parse(headRaw),rdfLock=JSON.parse(await readFile(path.join(data,'semantic/rdf-lock.json'),'utf8'));
const supportRaw=await readFile(path.join(data,'semantic/support-graph.json'),'utf8'),support=JSON.parse(supportRaw),supportProfile=JSON.parse(await readFile(path.join(data,'semantic/support-profile.json'),'utf8'));
const criticalMobileCss=await readFile(path.join(root,'src/styles/critical-mobile.css'),'utf8'),documentHeadSource=await readFile(path.join(root,'src/components/DocumentHead.astro'),'utf8');
const deployWorkflow=await readFile(path.join(root,'.github/workflows/deploy-cloudflare-pages.yml'),'utf8'),cloudflareEdgeSource=await readFile(path.join(root,'scripts/configure-cloudflare-edge.py'),'utf8');
if(/\/accounts\/\{account\}\/tokens/.test(deployWorkflow))fail('Deploy workflow must never mint temporary Cloudflare API tokens');
if(!deployWorkflow.includes('python scripts/configure-cloudflare-edge.py --apply')||!deployWorkflow.includes('--outcome edge-reconciliation.json')||!deployWorkflow.includes('EDGE_RECONCILIATION_OUTCOME: edge-reconciliation.json')||!deployWorkflow.includes('npm run verify:production'))fail('Deploy workflow is missing capability-aware edge reconciliation or full production verification');
for(const invariant of ['ghezelbaash_canonical_dist_cache_v1','ghezelbaash_canonical_hsts_v1','ghezelbaash_real_404_headers_v1','http.response.code eq 404','crawler_hints','ai_bots_protection','respect_origin','scopeGaps'])if(!cloudflareEdgeSource.includes(invariant))fail(`Cloudflare edge contract missing ${invariant}`);
if(pkg.version!==inv.release||release.release!==inv.release) fail('Release mismatch');
if(release.dateModified!==inv.date) fail(`Release freshness drift ${release.dateModified}/${inv.date}`);
if(!pkg.engines.node.includes('24.18.0')) fail('Node 24.18.0 pin missing');
for(const x of [...inv.aliases,inv.postalCode,inv.placeId,inv.googleKg,inv.clinicKg]) if(!graphText.includes(x)&&!content.includes(x)) fail(`Missing canonical truth ${x}`);
const stalePlace=['ChIJBT','OYDOTt-j8RD-7mAPy6Zas'].join('');
if(graphText.includes(stalePlace)||content.includes(stalePlace)) fail('Stale Place ID in semantic/human source');
if(!content.includes('جمعه تعطیل')) fail('Owner-confirmed Friday closure missing from visible content');
if(release.clinic.postalCode!==inv.postalCode||!graphText.includes(inv.postalCode)) fail('Owner-confirmed postal code missing from release/graph');
if(release.clinic.priceRange!==inv.priceRange) fail('Owner-confirmed clinic priceRange drift');
if(!robots.includes('Content-Signal: search=yes, ai-input=yes, ai-train=yes, use=full')) fail('robots Content-Signal missing');
for(const bot of ['Google-Extended','Google-CloudVertexBot','GPTBot','OAI-SearchBot','ChatGPT-User','ClaudeBot','Claude-SearchBot','Claude-User','PerplexityBot','Perplexity-User','Applebot','Applebot-Extended','DuckAssistBot','Cloudflare-AI-Search']) if(!robots.includes(`User-agent: ${bot}\nAllow: /`)) fail(`AI/search crawler explicit allow missing: ${bot}`);
if(headersTemplate.includes('/.well-known/security.txt')) fail('Dead security.txt header rule must not ship');
const machinePolicyResources=['graph.jsonld','graph.ttl','entity-facts.csv','answers.txt','knowledge.xml','llms.txt','index.md','llms-full.txt','datapackage.json','linkset.json','void.ttl','dcat.ttl','croissant.json','provenance.jsonld','evidence-snapshot.json','shapes.ttl','artifact-manifest.json'];
const headerBlock=(route)=>{const ls=headersTemplate.split(/\r?\n/),i=ls.findIndex(x=>x===`/${route}`);if(i<0)return'';const out=[ls[i]];for(let j=i+1;j<ls.length&&/^  /.test(ls[j]);j++)out.push(ls[j]);return out.join('\n')};
for(const rel of machinePolicyResources){const b=headerBlock(rel);if(!b.includes('X-Robots-Tag: index, follow, max-snippet:-1')||!b.includes('X-Robots-Tag: googlebot: noindex, follow'))fail(`Machine Search/agent policy drift ${rel}`)}
if(!/\/\n\s+Content-Type: text\/html[\s\S]{0,250}X-Robots-Tag: index, follow/.test(headersTemplate)) fail('Canonical HTML indexing rule missing');

// Canonical modular source must deterministically reproduce home.md.
const assembledCanonical=await assembleCanonicalContent({root,graph}),sectionNames=assembledCanonical.names;
if(sectionNames.length<100) fail('Modular source is not sufficiently sectioned');
if(assembledCanonical.content!==content) fail('Generated home.md drifted from modular canonical source and integrated native answers');
if(assembledCanonical.inserted!==inv.directAnswerExecutiveCount) fail(`Integrated native answer count drift ${assembledCanonical.inserted}`);
if(assembledCanonical.fullInserted!==inv.integratedFullAnswerCount) fail(`Integrated full native answer count drift ${assembledCanonical.fullInserted}`);
// Render calibration is a measured, hashed release artifact.
const chunkHeightBytes=await readFile(path.join(root,'src/data/render-calibration.json')),chunkHeights=JSON.parse(chunkHeightBytes),calWidths=[360,390,430,768,1024,1440];
const calBase=(chunkHeights['360']?.chunks||[]).map(x=>x.id);if(calBase.length!==inv.renderChunkCount||new Set(calBase).size!==inv.renderChunkCount) fail('Chunk calibration ID/count drift');
for(const w of calWidths){const rows=chunkHeights[String(w)]?.chunks||[];if(rows.length!==inv.renderChunkCount||rows.some((x,i)=>x.id!==calBase[i]||!Number.isFinite(Number(x.h))||Number(x.h)<=0)) fail(`Invalid chunk calibration at ${w}px`)}
const calibrationSha=sha(chunkHeightBytes);if(!css.includes(`/*DIST_CHUNK_CALIBRATION_SHA256:${calibrationSha}*/`)) fail('Measured render calibration hash drifted from CSS');
if((css.match(/#rc\d+\{--cis:/g)||[]).length!==inv.renderChunkCount*7) fail('Render calibration rule count drift');
if(!css.includes('/*DIST_CHUNK_INTRINSIC_START*/')||!css.includes('/*DIST_CHUNK_INTRINSIC_END*/')) fail('Render calibration boundaries missing');
const cssSplitMarker='/*DIST_CRITICAL_CSS_END*/',cssSplitAt=css.indexOf(cssSplitMarker);if(cssSplitAt<0||css.indexOf(cssSplitMarker,cssSplitAt+1)>=0)fail('Critical CSS split marker drift');const cssExternalAt=cssSplitAt+cssSplitMarker.length,criticalCss=css.slice(0,cssExternalAt)+criticalMobileCss,externalCss=css.slice(cssExternalAt),externalCssHash=sha(Buffer.from(externalCss)).slice(0,12),externalCssRel=`public/assets/site.${externalCssHash}.css`;if(Buffer.byteLength(criticalCss)>inv.maxCriticalCssBytes||Buffer.byteLength(externalCss)<inv.minExternalCssBytes)fail(`CSS budget split drift critical=${Buffer.byteLength(criticalCss)} external=${Buffer.byteLength(externalCss)}`);const generatedExternalCss=await readFile(path.join(root,externalCssRel),'utf8');if(generatedExternalCss!==externalCss)fail('Generated external CSS does not match canonical stylesheet remainder');if(!externalCss.includes(`/*DIST_CHUNK_CALIBRATION_SHA256:${calibrationSha}*/`)||criticalCss.includes('/*DIST_CHUNK_INTRINSIC_START*/'))fail('Render calibration must live in external CSS');for(const token of ['.skip-link{position:fixed','@media(max-width:48rem){:root{font-family:system-ui','padding:1rem .85rem calc(7.2rem + env(safe-area-inset-bottom))','h1{font-size:clamp(1.85rem,8.3vw,2.65rem)'])if(!criticalMobileCss.includes(token))fail(`Mobile critical rendering invariant missing: ${token}`);
const retrievalHeadingAliases=[...content.matchAll(/<h[2-4]\b[^>]*data-retrieval-alias=["']([^"']+)["'][^>]*>/gi)].map(m=>m[1]);
if(retrievalHeadingAliases.length!==inv.exactBestDoctorHeadingCount) fail(`Clinical retrieval-alias heading contract drift ${retrievalHeadingAliases.length}`);
const exactBestDoctorH4=[...content.matchAll(/<h4\b[^>]*data-retrieval-alias=["'][^"']+["'][^>]*>\s*<a\b[^>]*href=["']https:\/\/www\.instagram\.com\/doctor\.ghezelbaash\/["'][^>]*rel=["']external me noopener["'][^>]*>\s*([^<]*بهترین دکتر[^<]*)<\/a>\s*<\/h4>/gi)];
if(exactBestDoctorH4.length!==inv.exactBestDoctorHeadingCount) fail(`Exact best-doctor H4 restore drift ${exactBestDoctorH4.length}`);
const instagramHeadingLinks=exactBestDoctorH4.length;if(instagramHeadingLinks!==inv.instagramHeadingLinkCount) fail(`Instagram heading-link restore drift ${instagramHeadingLinks}`);
if(content.includes('id="best-doctor-query-matrix"')||!content.includes('id="verified-physician-identity-core"')) fail('Retired query matrix returned or visible identity core is missing');
const contentContract=inspectHtml(content,{wrapMain:true}),nativeBestHeadings=contentContract.headings.filter(node=>node.tagName==='h4'&&attr(node,'data-retrieval-alias'));
if(nativeBestHeadings.length!==inv.exactBestDoctorHeadingCount||nativeBestHeadings.some(node=>!nearest(node,parent=>parent.tagName==='section'&&classes(parent).has('content-section')))) fail('Best-doctor headings must each belong to a native clinical content section');
if(!content.includes('id="medical-content-governance"')||!content.includes('اطلاعات حساس پزشکی')||!content.includes('جایگزین معاینه، تشخیص فردی یا ارزیابی اورژانسی نیست')) fail('Visible medical governance/trust layer missing');

const flat=v=>Array.isArray(v)?v:[v].filter(Boolean), refs=v=>flat(v).map(x=>x?.['@id']).filter(Boolean), text=v=>flat(v).map(x=>x?.['@value']??x).join(' | ');
const durationSeconds=v=>{const m=String(v??'').match(/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+(?:\.\d+)?)S)?$/);return m?(Number(m[1]||0)*3600+Number(m[2]||0)*60+Number(m[3]||0)):NaN};
const byId=new Map(graph['@graph'].filter(n=>n['@id']).map(n=>[n['@id'],n]));
const person=byId.get(release.primaryEntity.id),clinic=byId.get(release.clinic.id),webpage=byId.get(`${release.canonicalUrl}#webpage`),website=byId.get(`${release.canonicalUrl}#website`);
if(!person||!clinic||!webpage||!website) fail('Core entity missing');
if(webpage.dateModified!==inv.date||website.dateModified!==inv.date)fail(`Core document freshness drift webpage=${webpage.dateModified} website=${website.dateModified}`);
if(clinic.priceRange!==inv.priceRange) fail('Clinic priceRange missing from canonical graph');
const fridayId=`${release.canonicalUrl}#clinic-friday-closed`,friday=byId.get(fridayId);if(!friday||!flat(friday['@type']).includes('OpeningHoursSpecification')||!text(friday.dayOfWeek).includes('Friday')||friday.opens!=='00:00'||friday.closes!=='00:00'||!refs(clinic.openingHoursSpecification).includes(fridayId)) fail('Owner-confirmed Friday closure is not modeled as OpeningHoursSpecification 00:00-00:00');
const alt=flat(person.alternateName).map(x=>x?.['@value']??x),expected=[...release.primaryEntity.officialAliases,...(release.primaryEntity.reconciliationAliases||[])];
if(expected.some(x=>!alt.includes(x))||alt.some(x=>!expected.includes(x))) fail('Person.alternateName does not match official + reconciliation tiers');
for(const x of release.primaryEntity.retrievalVariants) if(alt.includes(x)) fail(`Retrieval-only variant leaked into Person.alternateName: ${x}`);
if(text(person.familyName).includes('Ghezelbaash')||!text(person.familyName).includes('Ghezelbash')) fail('Canonical family name drift');
if(!text(website.name).includes('Dr. Saeed Ghezelbash')||text(website.name).includes('Dr. Saeed Ghezelbaash')) fail('WebSite English name drift');
if(!String(webpage.name).startsWith('دکتر سعید قزلباش')) fail('WebPage name is not entity-first');
if(!content.startsWith('---\ntitle: "دکتر سعید قزلباش | پزشک زیبایی در کرمانشاه"')) fail('Frontmatter title is not entity-first');
if(content.includes('no later release version is asserted')) fail('Obsolete v1 current-release assertion remains in visible content');
const fmDescription=(content.match(/^description:\s*"([^"]+)"/m)||[])[1];if(!fmDescription||String(webpage.description)!==fmDescription) fail('WebPage.description drifted from canonical meta description');
const sourceDataPackage=JSON.parse(await readFile(path.join(data,'projections/datapackage.json'),'utf8')),sourceCroissant=JSON.parse(await readFile(path.join(data,'projections/croissant.json'),'utf8')),sourceDcat=await readFile(path.join(data,'projections/dcat.ttl'),'utf8'),sourceVoid=await readFile(path.join(data,'projections/void.ttl'),'utf8');
if(sourceDataPackage.version!==inv.release||sourceCroissant.version!==inv.release||!sourceDcat.includes(`schema:version "${inv.release}"`)||!sourceVoid.includes(`void:triples ${inv.externalRdfTripleCount}`)) fail('Source descriptor release/triple metadata drift');
for(const f of ['public/doctor.vcf','public/clinic.vcf']){const v=await readFile(path.join(root,f),'utf8'),u=v.replace(/\r?\n[ \t]/g,'');if(!u.includes(`X-ENTITY-VERSION:${inv.release}`)||!u.includes(`Entity Contact Projection ${inv.release}`)||!u.includes(`REV:${inv.date.replaceAll('-','')}T000000Z`)||u.includes('ساختمانویستا')) fail(`vCard release/address drift: ${f}`);for(const m of u.matchAll(/https:\/\/www\.ghezelbaash\.ir\/(media\/[^\r\n;]+)/g)){const rel=m[1].split(/[?#]/)[0];if(!await access(path.join(root,'public',rel)).then(()=>true).catch(()=>false)) fail(`Broken first-party vCard media URL in ${f}: ${rel}`)}}
for(const f of ['public/favicon.svg','public/safari-pinned-tab.svg','public/media/brand/doctor-ghezelbaash-symbol.3a9e7509912d.svg']){const v=await readFile(path.join(root,f),'utf8');if(!v.includes(`<entity:Version>${inv.release}</entity:Version>`)) fail(`Entity media release metadata drift: ${f}`)}
const hasRef=(obj,key,id)=>refs(obj[key]).includes(id);
if(!hasRef(person,'owns',release.clinic.id)||!hasRef(person,'practicesAt',release.clinic.id)||!hasRef(person,'worksFor',release.clinic.id)||!hasRef(person,'affiliation',release.clinic.id)||!hasRef(person,'memberOf',release.clinic.id)||!hasRef(clinic,'owner',release.primaryEntity.id)||!hasRef(clinic,'founder',release.primaryEntity.id)||!hasRef(clinic,'employee',release.primaryEntity.id)) fail('Physician->clinic ownership/employment hierarchy broken');
for(const type of ['Person','IndividualPhysician'])if(!flat(person['@type']).includes(type))fail(`Physician type missing ${type}`);for(const type of ['MedicalClinic','PhysiciansOffice','LocalBusiness'])if(!flat(clinic['@type']).includes(type))fail(`Clinic type missing ${type}`);
const cryoId=`${release.canonicalUrl}#procedure-cryolipolysis-localized-fat-reduction`,doctorServices=refs(person.availableService),clinicServices=refs(clinic.availableService);if(doctorServices.includes(cryoId)||clinicServices.includes(cryoId)||!refs(person.knowsAbout).includes(cryoId)||!content.includes('کرایولیپولیز')||!content.includes('ارائه یا توصیه نمی‌شود')||!content.includes('منسوخ'))fail('Cryolipolysis educational-only boundary drift');
const availableIds=new Set([...doctorServices,...clinicServices]);if(doctorServices.length!==124||clinicServices.length!==123)fail(`Available-service counts drift physician=${doctorServices.length} clinic=${clinicServices.length}`);for(const id of availableIds){const service=byId.get(id);if(!flat(service?.['@type']).includes('Service')||refs(service?.provider).length!==1||!refs(service?.provider).includes(release.primaryEntity.id))fail(`Physician provider edge missing for ${id}`)}
if(!hasRef(webpage,'mainEntity',release.primaryEntity.id)||!hasRef(webpage,'author',release.primaryEntity.id)||!hasRef(webpage,'publisher',release.primaryEntity.id)) fail('Physician not dominant WebPage entity');
for(const id of [`${release.canonicalUrl}#action-contact-clinic`,`${release.canonicalUrl}#action-online-initial-consultation`,`${release.canonicalUrl}#action-view-clinic-map`,`${release.canonicalUrl}#action-follow-instagram`]) if(!refs(person.potentialAction).includes(id)||!refs(webpage.potentialAction).includes(id)) fail(`Action not connected to primary entity/page: ${id}`);
if(!hasRef(clinic,'contactPoint',`${release.canonicalUrl}#online-consultation-contact-point`)) fail('Clinic contactPoint missing');
const logo=byId.get(`${release.canonicalUrl}#image-doctor-ghezelbaash-clinic-logo`);if(flat(logo?.identifier).some(x=>/^Q\d+$/.test(String(x)))) fail('Person/Clinic QID incorrectly used as ImageObject identifier');
if(webpage.primaryImageOfPage?.['@id']!==`${release.canonicalUrl}#image-saeed-ghezelbash-portrait-master`) fail('Canonical portrait chain broken');

// Early graph: compact, connected, physician-first.
if(Buffer.byteLength(headRaw)>inv.maxHeadGraphBytes) fail(`Head graph exceeds ${inv.maxHeadGraphBytes}`);
const headIds=new Set(head['@graph'].map(n=>n['@id'])); const incoming=new Map([...headIds].map(x=>[x,0]));
function scan(v,owner){if(Array.isArray(v))for(const x of v)scan(x,owner);else if(v&&typeof v==='object'){if(v['@id']&&headIds.has(v['@id'])&&v['@id']!==owner)incoming.set(v['@id'],incoming.get(v['@id'])+1);for(const x of Object.values(v))scan(x,owner)}}
for(const n of head['@graph']) scan(n,n['@id']);
const coreRoots=new Set([release.primaryEntity.id,`${release.canonicalUrl}#webpage`,`${release.canonicalUrl}#website`]);
const orphan=[...incoming].filter(([id,c])=>c===0&&!coreRoots.has(id)).map(([id])=>id);if(orphan.length) fail(`Detached Head nodes: ${orphan.join(',')}`);
const headPerson=head['@graph'].find(n=>n['@id']===release.primaryEntity.id);if((headPerson?.availableService||headPerson?.subjectOf)) fail('Long-tail Person edges leaked into Head');
const headPage=head['@graph'].find(n=>n['@id']===`${release.canonicalUrl}#webpage`);if(headPage?.hasPart||headPage?.citation||headPage?.mentions) fail('Long-tail WebPage edges leaked into Head');
if(Buffer.byteLength(supportRaw)>inv.maxSupportGraphBytes||supportProfile.maxBytes!==inv.maxSupportGraphBytes) fail(`Support Graph budget drift: ${Buffer.byteLength(supportRaw)}`);
// Extreme-ceiling identity lane: Head keeps only strongest externally corroborated aliases/identity anchors.
if((flat(headPerson?.sameAs)).length!==inv.headSameAsCount) fail(`Head sameAs count drift ${(flat(headPerson?.sameAs)).length}`);
if((flat(headPerson?.alternateName)).length!==inv.headAlternateNameCount) fail(`Head alternateName count drift ${(flat(headPerson?.alternateName)).length}`);
if(!headPage?.speakable) fail('Early speakable restoration missing');
// Full graph closure: every named graph node must have an inbound relationship; redundant orphan nodes are forbidden.
const fullIds=new Set(graph['@graph'].filter(n=>n['@id']).map(n=>n['@id'])),fullIncoming=new Map([...fullIds].map(id=>[id,0]));
function scanFull(v,owner){if(Array.isArray(v))for(const x of v)scanFull(x,owner);else if(v&&typeof v==='object'){if(v['@id']&&fullIds.has(v['@id'])&&v['@id']!==owner)fullIncoming.set(v['@id'],fullIncoming.get(v['@id'])+1);for(const x of Object.values(v))scanFull(x,owner)}}
for(const n of graph['@graph']) scanFull(n,n['@id']);
const fullOrphans=[...fullIncoming].filter(([,c])=>c===0).map(([id])=>id);if(fullOrphans.length>inv.maxOrphanGraphNodes) fail(`Unjustified full-graph orphan nodes: ${fullOrphans.join(',')}`);
if(graph['@graph'].length!==inv.fullGraphNodeCount) fail(`Full graph node-count invariant drift ${graph['@graph'].length}`);
const supportClips=support['@graph'].filter(n=>flat(n['@type']).includes('Clip'));if(supportClips.length!==inv.inlineSemanticClipCount) fail(`Inline semantic Clip count mismatch ${supportClips.length}`);
const eligibleSupportClips=supportClips.filter(c=>{const parent=byId.get(c.isPartOf?.['@id']);return parent&&durationSeconds(parent.duration)>=30});if(eligibleSupportClips.length!==inv.inlineEligibleClipCount) fail(`Inline Google-eligible Clip count mismatch ${eligibleSupportClips.length}`);
const kurdishSupportClips=supportClips.filter(c=>String(c['@id']).includes('kurdish-patient-experience'));if(kurdishSupportClips.length!==3) fail(`Kurdish semantic Clip restoration drift ${kurdishSupportClips.length}`);
if(support['@graph'].length!==inv.supportNodeTarget) fail(`Support node target drift ${support['@graph'].length}/${inv.supportNodeTarget}`);
const fullClips=graph['@graph'].filter(n=>flat(n['@type']).includes('Clip'));for(const clip of fullClips){if(!Number.isInteger(clip.startOffset)||Object.hasOwn(clip,'endOffset')&&!Number.isInteger(clip.endOffset))fail(`Clip offsets must be integer-valued when present: ${clip['@id']}`)}if(fullClips.filter(clip=>!Object.hasOwn(clip,'endOffset')).length!==4)fail('Exactly four final clips must omit optional endOffset');
for(const image of graph['@graph'].filter(n=>flat(n['@type']).includes('ImageObject')))for(const key of ['license','copyrightNotice','acquireLicensePage','creditText'])if(!image[key])fail(`Image license field ${key} missing on ${image['@id']}`);if(!content.includes('id="media-license"')||!content.includes('CC BY 4.0'))fail('Visible clinic image license statement missing');

// RDF release lock: exact source+distribution bytes and declared triple count.
const ttl=await readFile(path.join(data,'semantic/knowledge-graph.ttl'));
if(rdfLock.release!==inv.release||rdfLock.jsonldSha256!==sha(Buffer.from(graphText))||rdfLock.ttlSha256!==sha(ttl)||rdfLock.triples!==inv.externalRdfTripleCount) fail('RDF lock mismatch');


// Public release/entity truth: Version 1.0.0 must be coherent across canonical source surfaces.
if(inv.release!=='1.0.0'||release.release!=='1.0.0') fail('Public release identity must be Version 1.0.0');
const publicReleaseFiles=['package.json','src/data/release.json','src/data/release-invariants.json','src/data/evidence-registry.json','src/data/evidence-snapshot.json','src/data/volatile-facts.json','src/content-source/100-rc099.html','src/data/semantic/knowledge-graph.jsonld','public/favicon.svg','public/safari-pinned-tab.svg'];
for(const rel of publicReleaseFiles){const txt=await readFile(path.join(root,rel),'utf8');if(/\b5\.0\.0\b|\bVersion 5\b|\bRelease 5\b/.test(txt))fail(`Legacy release-version residue: ${rel}`)}
if(content.includes('github.ghezelbaash.ir')) fail('Broken/ambiguous project interface must not be promoted by canonical HTML');
if(JSON.stringify(graph).includes('github.ghezelbaash.ir')||byId.has(`${release.canonicalUrl}#project-public-interface`)) fail('Broken/ambiguous project interface remains in graph');
if(!content.includes('href="https://www.wikidata.org/wiki/Q140288589">Dr. Saeed Ghezelbash Aesthetic Clinic</a>')) fail('Q140288589 visible entity label drift');
if(content.includes('href="https://www.wikidata.org/wiki/Q140288589">Doctor Ghezelbash structured-data organization</a>')) fail('Clinic Wikidata ID mislabeled as structured-data organization');
const projectNode=byId.get(`${release.canonicalUrl}#doctor-ghezelbaash-structured-data-project`),zenodoNode=byId.get(`${release.canonicalUrl}#project-zenodo-release`),datasetNode=byId.get(`${release.canonicalUrl}graph.jsonld#dataset`);
for(const [label,node] of [['project',projectNode],['zenodo',zenodoNode],['dataset',datasetNode]])if(node?.version!=='1.0.0')fail(`${label} Version 1.0.0 drift`);
if(projectNode?.dateModified!=='2026-08-08')fail('Project dateModified drift');
if(zenodoNode?.dateModified)fail('Zenodo archival snapshot must not inherit live-source dateModified');

// Media: all metadata preserved but stale Place ID forbidden; fingerprints must equal bytes.
const mediaFiles=await walk(path.join(root,'public/media'));let currentPlaceHits=0;
for(const f of mediaFiles){const b=await readFile(f);if(b.includes(Buffer.from(stalePlace))) fail(`Stale Place ID in media metadata: ${path.relative(root,f)}`);if(b.includes(Buffer.from(inv.placeId))) currentPlaceHits++;const m=path.basename(f).match(/\.([0-9a-f]{12})\.[^.]+$/);if(!m) fail(`Media asset lacks fingerprint: ${path.relative(root,f)}`);const isSelfReferentialSvg=f.endsWith('.svg')&&b.includes(Buffer.from(path.basename(f)));if(isSelfReferentialSvg){if(!b.includes(Buffer.from(`https://www.ghezelbaash.ir/media/brand/${path.basename(f)}`))) fail(`Self-referential SVG URL mismatch: ${path.relative(root,f)}`)}else if(sha(b).slice(0,12)!==m[1]) fail(`Media fingerprint mismatch: ${path.relative(root,f)}`)}
if(currentPlaceHits<20) fail(`Expected entity metadata Place ID in media; found ${currentPlaceHits}`);

// Performance/UX architecture gates.
if(css.includes(':has(:target)')) fail('Expensive :has(:target) remains on mega-page chunks');
if(!css.includes('.render-chunk.is-target-chunk')) fail('Target chunk class strategy missing');
if(!guide.includes("addEventListener('hashchange',syncTarget")||!guide.includes("e.key==='/'")) fail('Guide navigation progressive enhancement missing');
if(!guide.includes("main h2[id],main h3[id],main h4[id]")||!guide.includes('data-entity-aliases')) fail('Guide Search does not cover H2-H4 plus entity aliases');
if(!guide.includes('x.dataset.retrievalAlias')||!guide.includes("text+' '+headingAlias")) fail('Guide Search does not preserve clinical retrieval heading aliases');
if(!content.includes('aria-keyshortcuts="/"')||!content.includes('aria-haspopup="dialog"')) fail('Accessible Guide search trigger metadata missing');
const captionTracks=[...content.matchAll(/<track\b[^>]*kind=["']captions["'][^>]*src=["']([^"']+)["'][^>]*>/gi)].map(m=>m[1]);if(captionTracks.length!==inv.captionTrackTarget) fail(`Verified caption track count mismatch ${captionTracks.length}`);for(const u of captionTracks){if(!/\.captions\.fa\.[0-9a-f]{12}\.vtt$/.test(u))fail(`Caption track not fingerprinted/typed ${u}`);const b=await readFile(path.join(root,'public',u.slice(1)),'utf8');if(!b.startsWith('WEBVTT')||!b.includes('Verified transcription of burned-in Persian subtitles'))fail(`Caption provenance missing ${u}`)}for(const id of [`${release.canonicalUrl}#video-jalupro-vs-profhilo`,`${release.canonicalUrl}#video-subcision-technique`]){const v=byId.get(id);if(!v?.transcript||!v?.caption)fail(`Verified VideoObject transcript/caption missing ${id}`)}for(const id of [`${release.canonicalUrl}#video-thread-lift-workshop`,`${release.canonicalUrl}#video-kurdish-patient-experience`]){const v=byId.get(id);if(v?.transcript||v?.caption)fail(`Unverified transcript/caption fabricated ${id}`)}
if(!css.includes('@media(prefers-contrast:more)')) fail('High-contrast UX enhancement missing');

// Evidence/claim provenance and SHACL constitution are release artifacts, not decorative files.
const evidenceRegistry=JSON.parse(await readFile(path.join(data,'evidence-registry.json'),'utf8'));
const evidenceSnapshot=JSON.parse(await readFile(path.join(data,'evidence-snapshot.json'),'utf8'));
const provenance=JSON.parse(await readFile(path.join(data,'projections/provenance.jsonld'),'utf8'));
const shapes=await readFile(path.join(data,'semantic/shapes.ttl'),'utf8');
const tierAIds=new Set((evidenceRegistry.evidence||[]).filter(x=>x.tier==='A').map(x=>x.id));
if(tierAIds.size<8||evidenceSnapshot.release!==inv.release) fail('Evidence registry/snapshot release contract drift');
const provNodes=provenance['@graph']||[],provPassages=provNodes.filter(n=>String(n['@id']||'').includes('provenance.jsonld#passage-')),provAnswers=provNodes.filter(n=>String(n['@id']||'').includes('provenance.jsonld#answer-'));
const provenanceExpectedPassages=(llmsFull.match(/^\[PASSAGE\]$/gm)||[]).length;if(provPassages.length!==provenanceExpectedPassages||provAnswers.length!==125) fail(`Provenance coverage drift passages=${provPassages.length}/${provenanceExpectedPassages} answers=${provAnswers.length}/125`);
const knownEvidence=new Set((evidenceRegistry.evidence||[]).map(x=>x.id));
let claimPrimarySourceNodes=0;for(const n of [...provPassages,...provAnswers]){const digest=flat(n.identifier).find(x=>x?.propertyID==='SHA-256')?.value;if(!/^[0-9a-f]{64}$/.test(String(digest||'')))fail(`Provenance SHA-256 missing ${n['@id']}`);const derived=refs(n['prov:wasDerivedFrom']);if(!derived.length)fail(`Canonical source provenance missing ${n['@id']}`);const claimSources=refs(n['prov:hadPrimarySource']);for(const id of claimSources)if(!knownEvidence.has(id))fail(`Unknown claim evidence ${id} on ${n['@id']}`);if(claimSources.length)claimPrimarySourceNodes++;}
if(claimPrimarySourceNodes<10)fail(`Explicit claim-evidence coverage unexpectedly sparse ${claimPrimarySourceNodes}`);
for(const ev of evidenceRegistry.evidence||[]){if(!provNodes.some(n=>n['@id']===ev.id&&n.url===ev.url&&String(n.additionalType||'')===`EvidenceTier${ev.tier}`))fail(`Evidence node missing from provenance graph ${ev.id}`)}
for(const token of ['sh:targetNode ex:saeed-ghezelbash','sh:hasValue ex:dr-saeed-ghezelbash-aesthetic-clinic-kermanshah','sh:targetNode ex:webpage','sh:hasValue "$$$$"']) if(!shapes.includes(token)) fail(`SHACL constitution invariant missing: ${token}`);

// Machine projections must now be truly structured and consolidated.
if(markdown===content||!markdown.startsWith('# دکتر سعید قزلباش')||(markdown.match(/^#{1,6} /gm)||[]).length<100) fail('index.md is not a true semantic Markdown projection');
const passages=(llmsFull.match(/^\[PASSAGE\]$/gm)||[]).length,declaredPassages=Number((llmsFull.match(/^PASSAGE_COUNT:\s*(\d+)/m)||[])[1]);if(passages<100||declaredPassages!==passages) fail(`llms-full passage count drift declared=${declaredPassages} emitted=${passages}`);if((llmsFull.match(/^EVIDENCE_IDS:/gm)||[]).length!==passages||(llmsFull.match(/^CLAIM_EVIDENCE_IDS:/gm)||[]).length!==passages||(llmsFull.match(/^ENTITY_EVIDENCE_IDS:/gm)||[]).length!==passages||(llmsFull.match(/^TIER_A_EVIDENCE_IDS:/gm)||[]).length!==passages||(llmsFull.match(/^GRAPH_NODE_ID:/gm)||[]).length!==passages) fail('RAG provenance fields missing from passages');const blocks=llmsFull.split(/^\[PASSAGE\]$/m).slice(1),passageIds=new Set();for(const b of blocks){const id=(b.match(/^PASSAGE_ID:\s*(\S+)/m)||[])[1],txt=(b.match(/^TEXT:\s*([\s\S]*?)\n\[\/PASSAGE\]/m)||[])[1]??'';if(!id||passageIds.has(id))fail(`Missing/duplicate passage id ${id}`);passageIds.add(id);if(txt.trim().length>inv.maxRagPassageChars)fail(`RAG passage too large ${id}: ${txt.trim().length}`);if(!/^SOURCE_HASH_SHA256:\s*[0-9a-f]{64}$/m.test(b))fail(`Passage source hash missing ${id}`)}
const ragEntityEvidenceNonEmpty=[...llmsFull.matchAll(/^ENTITY_EVIDENCE_IDS:[ \t]*(.+)$/gm)].filter(m=>m[1].trim()).length;const ragClaimEvidenceNonEmpty=[...llmsFull.matchAll(/^CLAIM_EVIDENCE_IDS:[ \t]*(.+)$/gm)].filter(m=>m[1].trim()).length;if(ragEntityEvidenceNonEmpty!==passages||ragClaimEvidenceNonEmpty<inv.minClaimEvidencePassages)fail(`RAG evidence tier coverage drift entity=${ragEntityEvidenceNonEmpty}/${passages} claim=${ragClaimEvidenceNonEmpty}`);
const answersProjection=await readFile(path.join(data,'projections/answers.txt'),'utf8');if((answersProjection.match(/^QUESTION_ID:/gm)||[]).length!==125||(answersProjection.match(/^SOURCE_HASH_SHA256:\s*[0-9a-f]{64}$/gm)||[]).length!==125||(answersProjection.match(/^EXECUTIVE_SUMMARY:/gm)||[]).length!==125||(answersProjection.match(/^EVIDENCE_IDS:/gm)||[]).length!==125||(answersProjection.match(/^CLAIM_EVIDENCE_IDS:/gm)||[]).length!==125||(answersProjection.match(/^ENTITY_EVIDENCE_IDS:/gm)||[]).length!==125) fail('Evidence-aware direct-answer projection incomplete');const executiveProjectionCount=[...answersProjection.matchAll(/^EXECUTIVE_SUMMARY:[ \t]*(.+)$/gm)].filter(m=>m[1].trim()).length,executiveHashCount=(answersProjection.match(/^EXECUTIVE_SUMMARY_HASH_SHA256:\s*[0-9a-f]{64}$/gm)||[]).length;if(executiveProjectionCount!==inv.directAnswerExecutiveCount||executiveHashCount!==inv.directAnswerExecutiveCount)fail(`Executive-answer projection drift ${executiveProjectionCount}/${executiveHashCount}`);const answerEntityEvidenceNonEmpty=[...answersProjection.matchAll(/^ENTITY_EVIDENCE_IDS:[ \t]*(.+)$/gm)].filter(m=>m[1].trim()).length;if(answerEntityEvidenceNonEmpty<20)fail(`Answer entity-evidence coverage unexpectedly sparse ${answerEntityEvidenceNonEmpty}`);
if(!llmsFull.includes(`IDENTITY_FINGERPRINT_SHA256: ${inv.identityFingerprintSha256}`)) fail('Identity fingerprint hash drift in RAG projection');
const sitemapText=await readFile(path.join(data,'projections/sitemap.xml'),'utf8');
const sitemapUrlCount=(sitemapText.match(/<url>/g)||[]).length;if(sitemapUrlCount!==inv.googleSearchLandingCount||!sitemapText.includes(`<loc>${release.canonicalUrl}</loc>`)) fail(`Google-facing sitemap landing count drift ${sitemapUrlCount}`);for(const rel of machinePolicyResources)if(sitemapText.includes(`<loc>${release.canonicalUrl}${rel}</loc>`))fail(`Machine representation leaked into Google-facing sitemap ${rel}`);
for(const d of [...sitemapText.matchAll(/<video:duration>([^<]+)<\/video:duration>/g)].map(m=>m[1])) if(!/^\d+$/.test(d)||Number(d)<1||Number(d)>28800) fail(`Invalid video sitemap duration ${d}`);
if(!llms.includes('Verified reconciliation aliases')||!llms.includes('retrieval variants (not canonical names)')) fail('Alias taxonomy missing in llms.txt');
for(const a of release.primaryEntity.officialAliases) if(!llms.includes(a)) fail(`Official alias missing in llms ${a}`);
for(const a of release.primaryEntity.reconciliationAliases||[]) if(!llms.includes(a)) fail(`Reconciliation alias missing in llms ${a}`);
for(const a of release.primaryEntity.retrievalVariants) if(!llms.includes(a)) fail(`Retrieval variant missing in llms ${a}`);
if(!llms.includes('googlebot: noindex, follow')||!llms.includes('sole sitemap-declared Search landing'))fail('llms machine/Search hierarchy policy drift');


// Source-level HTML/reference integrity, so the repository can fail before Astro compilation.
const footer=await readFile(path.join(data,'templates/footer.html'),'utf8'),quick=await readFile(path.join(data,'templates/quick-actions.html'),'utf8'),mainHead=await readFile(path.join(data,'templates/main-head.html'),'utf8'),baseLayoutSource=await readFile(path.join(root,'src/layouts/BaseLayout.astro'),'utf8');
const heroPreloadTags=[...mainHead.matchAll(/<link\b(?=[^>]*\brel="preload")(?=[^>]*\bas="image")(?=[^>]*\bfetchpriority="high")(?=[^>]*\bimagesrcset=)(?=[^>]*\bimagesizes=)(?=[^>]*saeed-ghezelbash-portrait-delivery-640)[^>]*\/>/gi)];if(heroPreloadTags.length!==1)fail(`Responsive Hero preload source drift ${heroPreloadTags.length}`);if(!documentHeadSource.includes('mainHeadWithoutCriticalHints')||!documentHeadSource.includes('<Fragment set:html={viewportTag} /><Fragment set:html={heroPreloadTag} />'))fail('Responsive Hero preload is not promoted immediately after viewport');
const relMeHrefs=[...mainHead.matchAll(/<link\b[^>]*>/gi)].map(m=>m[0]).filter(t=>/\brel=["']me["']/i.test(t)).map(t=>(t.match(/\bhref=["']([^"']+)["']/i)||[])[1]).filter(Boolean);if(new Set(relMeHrefs).size<inv.headSameAsCount) fail(`rel=me identity mesh too small ${new Set(relMeHrefs).size}`);for(const u of flat(headPerson?.sameAs)) if(!relMeHrefs.some(x=>x===String(u)||x.replace(/\/$/,'')===String(u).replace(/\/$/,''))) fail(`Head sameAs missing rel=me identity link ${u}`);
const answerNodes=new Map(graph['@graph'].filter(n=>flat(n['@type']).includes('Answer')).map(n=>[n['@id'],n]));const strip=x=>String(x).replace(/<script\b[\s\S]*?<\/script>/gi,' ').replace(/<style\b[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();const visibleBody=strip(content),visibleCanonicalAnswers=[...answerNodes.values()].filter(a=>strip(a.text)&&visibleBody.includes(strip(a.text))).length;if(visibleCanonicalAnswers!==inv.canonicalAnswerTextVisibleCount)fail(`Canonical Answer.text visible coverage drift ${visibleCanonicalAnswers}/${inv.canonicalAnswerTextVisibleCount}`);let integratedExecutiveAnswers=0;for(const a of answerNodes.values())if(a.description){integratedExecutiveAnswers++;const d=strip(a.description),count=d?visibleBody.split(d).length-1:0;if(count!==1)fail(`Integrated Answer.description visibility/uniqueness drift ${a['@id']} count=${count}`)}if(integratedExecutiveAnswers!==inv.directAnswerExecutiveCount||content.includes('direct-answer-capsules')||content.includes('data-answer-id='))fail('Retired answer-capsule projection returned');
if(!baseLayoutSource.includes('data-deferred-stylesheet')||!baseLayoutSource.includes('rel="preload"')||!baseLayoutSource.includes('deferred-stylesheet-loader')||!baseLayoutSource.includes("criticalMobileCss from '../styles/critical-mobile.css?raw'")||!baseLayoutSource.includes('criticalCss')||!baseLayoutSource.includes('id="entity-support"'))fail('Base layout asynchronous CSS/support hardening missing');if(!headersTemplate.includes('/assets/*')||!headersTemplate.includes('max-age=31536000, immutable'))fail('Fingerprint CSS immutable header rule missing');
const assembledUi=`${content}\n${footer}\n${quick}\n${guide}`;
assertDocumentContract(assembledUi,{wrapMain:true,expectedContentSections:inv.contentSectionCount});
const endpointPaths=new Set(['/','/graph.jsonld','/graph.ttl','/entity-facts.csv','/answers.txt','/knowledge.xml','/llms.txt','/llms-full.txt','/index.md','/datapackage.json','/linkset.json','/void.ttl','/dcat.ttl','/croissant.json','/provenance.jsonld','/evidence-snapshot.json','/shapes.ttl','/sitemap.xml','/artifact-manifest.json']);
const localPaths=new Set();for(const textBlob of [content,mainHead,footer,quick,guide,await readFile(path.join(root,'public/site.webmanifest'),'utf8')]){for(const m of textBlob.matchAll(/\b(?:src|href|poster)=["'](\/[^"'#?]*)/gi)) localPaths.add(m[1]);for(const m of textBlob.matchAll(/\bsrcset=["']([^"']+)/gi)) for(const part of m[1].split(',')){const u=part.trim().split(/\s+/)[0];if(u.startsWith('/'))localPaths.add(u.split(/[?#]/)[0])}}
for(const u of localPaths){if(endpointPaths.has(u)||u.endsWith('/'))continue;const target=path.join(root,'public',u.slice(1));if(!await access(target).then(()=>true).catch(()=>false)) fail(`Missing source-referenced local asset: ${u}`)}
const headerLines=headersTemplate.split(/\r?\n/);if(headerLines.some(l=>l.trim().length>2000)) fail('Cloudflare header line exceeds 2000 chars');const headerRuleCount=headerLines.filter(l=>l&&!/^\s/.test(l)&&!l.startsWith('#')).length;if(headerRuleCount>100) fail(`Cloudflare _headers rule count ${headerRuleCount}>100`);

const packageScript=await readFile(path.join(root,'scripts/package-dist.mjs'),'utf8');if(packageScript.includes('dist-v1')||!packageScript.includes('releaseMeta.release')) fail('Release package naming is not dynamic/current');
const pages=await readdir(path.join(root,'src/pages'));if(pages.some(x=>x.includes('[...'))) fail('Dynamic catch-all forbidden');
const layout=await readFile(path.join(root,'src/layouts/BaseLayout.astro'),'utf8');if(/client:(load|idle|visible|media|only)/.test(layout)) fail('Hydrated island found');
if(await access(path.join(root,'public/.well-known/security.txt')).then(()=>true).catch(()=>false)) fail('Non-operational security.txt must not ship');
console.log(JSON.stringify({valid:true,release:inv.release,pages:pages.length,graphNodes:graph['@graph'].length,headNodes:head['@graph'].length,headBytes:Buffer.byteLength(headRaw),supportBytes:Buffer.byteLength(supportRaw),inlineSemanticClips:supportClips.length,inlineEligibleClips:eligibleSupportClips.length,captionTracks:captionTracks.length,aliases:{official:release.primaryEntity.officialAliases.length,reconciliation:(release.primaryEntity.reconciliationAliases||[]).length,retrieval:release.primaryEntity.retrievalVariants.length},mediaFiles:mediaFiles.length,mediaWithCurrentPlaceId:currentPlaceHits,contentSourceFiles:sectionNames.length,markdownHeadings:(markdown.match(/^#{1,6} /gm)||[]).length,llmPassages:(llmsFull.match(/^\[PASSAGE\]$/gm)||[]).length},null,2));
