import path from 'node:path';
import {createHash} from 'node:crypto';
import {readFile,readdir,access} from 'node:fs/promises';
const root=process.cwd(),dist=path.resolve(root,process.argv[2]||'dist'),data=path.join(root,'src/data');
const readJson=async p=>JSON.parse(await readFile(p,'utf8')),fail=m=>{throw new Error(m)},arr=v=>Array.isArray(v)?v:(v==null?[]:[v]),id=v=>typeof v==='string'?v:v?.['@id'],types=n=>arr(n?.['@type']),refs=v=>arr(v).map(id).filter(Boolean),sha=b=>createHash('sha256').update(b).digest('hex'),b64=b=>createHash('sha256').update(b).digest('base64');
const release=await readJson(path.join(data,'release.json')),inv=await readJson(path.join(data,'release-invariants.json')),registry=await readJson(path.join(data,'service-registry.json')),answerRegistry=await readJson(path.join(data,'answer-registry.json')),volatile=await readJson(path.join(data,'volatile-facts.json')),queryPolicy=await readJson(path.join(data,'retrieval/query-matrix-policy.json'));
const required=['index.html','404.html','_headers','_redirects','artifact-manifest.json','live-serving-attestation.json','live-observations.jsonld','query-matrix.jsonl','current-release-matrix.json','graph.jsonld','graph.ttl','entity-facts.csv','answers.txt','knowledge.xml','llms.txt','llms-full.txt','index.md','datapackage.json','linkset.json','void.ttl','dcat.ttl','croissant.json','provenance.jsonld','evidence-snapshot.json','shapes.ttl','sitemap.xml','robots.txt'];for(const f of required)await access(path.join(dist,f));
const html=await readFile(path.join(dist,'index.html'),'utf8'),htmlBytes=Buffer.byteLength(html),headers=await readFile(path.join(dist,'_headers'),'utf8'),robots=await readFile(path.join(dist,'robots.txt'),'utf8'),graphBytes=await readFile(path.join(dist,'graph.jsonld')),graph=JSON.parse(graphBytes),graphText=graphBytes.toString(),manifestBytes=await readFile(path.join(dist,'artifact-manifest.json')),manifest=JSON.parse(manifestBytes),att=JSON.parse(await readFile(path.join(dist,'live-serving-attestation.json'),'utf8')),liveBytes=await readFile(path.join(dist,'live-observations.jsonld')),live=JSON.parse(liveBytes),matrix=await readJson(path.join(dist,'current-release-matrix.json')),sitemap=await readFile(path.join(dist,'sitemap.xml'),'utf8');
if(htmlBytes>=inv.maxHtmlBytes)fail(`HTML safety ceiling exceeded ${htmlBytes}/${inv.maxHtmlBytes}`);if(inv.maxHtmlBytes+inv.googlebotReservedResponseHeaderBytes+inv.googlebotSafetyMarginBytes>inv.googlebotFetchBudgetBytes)fail('Response budget contract exceeds Googlebot budget');
if(!/<title>\s*دکتر سعید قزلباش \| پزشک زیبایی در کرمانشاه\s*<\/title>/i.test(html)||!/<h1\b[^>]*>[\s\S]*?دکتر سعید قزلباش؛ پزشک زیبایی در کرمانشاه/i.test(html))fail('Entity-first title/H1 regressed');if(!html.includes('google-maps-clinic-reputation-current'))fail('Visible Google reputation slot missing');if(!html.includes('جمعه تعطیل'))fail('Owner-confirmed Friday closure missing');
const cssSource=await readFile(path.join(root,'src/styles/global.css'),'utf8'),criticalMobile=await readFile(path.join(root,'src/styles/critical-mobile.css'),'utf8'),marker='/*DIST_CRITICAL_CSS_END*/',at=cssSource.indexOf(marker);if(at<0)fail('Critical CSS marker missing');const ext=cssSource.slice(at+marker.length),cssHash=sha(Buffer.from(ext)).slice(0,12),cssRel=`assets/site.${cssHash}.css`;if(await readFile(path.join(dist,cssRel),'utf8')!==ext)fail('Fingerprint CSS bytes drift');const siteAssets=(await readdir(path.join(dist,'assets'))).filter(x=>/^site\.[0-9a-f]{12}\.css$/.test(x));if(siteAssets.length!==1||siteAssets[0]!==path.basename(cssRel))fail('Stale fingerprint CSS asset shipped');const tags=[...html.matchAll(/<link\b[^>]*>/gi)].map(m=>m[0]);if(!tags.some(t=>t.includes(`href="/${cssRel}"`)&&/rel=["']preload["']/i.test(t)&&/as=["']style["']/i.test(t))||!tags.some(t=>t.includes(`href="/${cssRel}"`)&&/rel=["']stylesheet["']/i.test(t)))fail('Asynchronous CSS preload/fallback missing');const inlineStyles=[...html.matchAll(/<style(?:\s[^>]*)?>([\s\S]*?)<\/style>/gi)].map(m=>m[1]);if(inlineStyles.length!==1||inlineStyles[0]!==cssSource.slice(0,at+marker.length)+criticalMobile)fail('Critical inline CSS drift');
if(!robots.includes('Content-Signal: search=yes, ai-input=yes, ai-train=yes, use=full')||!headers.includes('Content-Signal: search=yes, ai-input=yes, ai-train=yes, use=full'))fail('Maximum Content-Signal policy missing');
const scripts=[...html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/gi)].map(m=>({attrs:m[1],body:m[2]})),ld=scripts.filter(x=>/application\/ld\+json/i.test(x.attrs)),exec=scripts.filter(x=>!/application\/ld\+json/i.test(x.attrs));const coreScript=ld.find(x=>/id=["']entity-core["']/i.test(x.attrs)),supportScript=ld.find(x=>/id=["']entity-support["']/i.test(x.attrs));if(ld.length!==2||!coreScript||!supportScript||exec.length!==2||!exec.some(x=>/id=["']site-runtime["']/i.test(x.attrs))||!exec.some(x=>/id=["']deferred-stylesheet-loader["']/i.test(x.attrs)))fail(`Inline script contract drift ld=${ld.length} exec=${exec.length}`);JSON.parse(coreScript.body);const support=JSON.parse(supportScript.body);if(Buffer.byteLength(coreScript.body)>inv.maxHeadGraphBytes||Buffer.byteLength(supportScript.body)>inv.maxSupportGraphBytes)fail('Inline semantic byte budget exceeded');const supportIds=new Set((support['@graph']||[]).map(n=>n['@id']));for(const forbidden of [`${release.canonicalUrl}#observation-clinic-google-rating-current`,`${release.canonicalUrl}#observation-clinic-google-review-count-current`,`${release.canonicalUrl}#speakable-primary-content`])if(supportIds.has(forbidden))fail(`Mutable/low-ROI node leaked into frozen support lane: ${forbidden}`);
const nodes=graph['@graph']||[],byId=new Map(nodes.filter(n=>n?.['@id']).map(n=>[n['@id'],n])),person=byId.get(release.primaryEntity.id),clinic=byId.get(release.clinic.id),dataset=byId.get(release.dataset.id),page=byId.get(`${release.canonicalUrl}#webpage`),site=byId.get(`${release.canonicalUrl}#website`);if(!person||!clinic||!dataset||!page||!site)fail('Core graph entity missing');if(id(dataset.creator)!==release.primaryEntity.id||id(dataset.publisher)!==release.primaryEntity.id||dataset.version!==release.release)fail('Dataset physician-first/version contract broken');const dSame=new Set(refs(dataset.sameAs));if(!dSame.has(`https://www.wikidata.org/entity/${release.dataset.wikidata}`)||[...dSame].some(x=>/github\.com|huggingface\.co|doi\.org|zenodo\.org/.test(x)))fail('Dataset identity/distribution topology collision');
for(const t of ['Person','IndividualPhysician'])if(!types(person).includes(t))fail(`Physician type missing ${t}`);for(const t of ['MedicalClinic','PhysiciansOffice','LocalBusiness'])if(!types(clinic).includes(t))fail(`Clinic type missing ${t}`);const has=(o,k,v)=>refs(o?.[k]).includes(v);if(!has(person,'owns',release.clinic.id)||!has(person,'practicesAt',release.clinic.id)||!has(clinic,'owner',release.primaryEntity.id)||!has(clinic,'founder',release.primaryEntity.id)||!has(page,'mainEntity',release.primaryEntity.id)||!has(page,'author',release.primaryEntity.id)||!has(page,'publisher',release.primaryEntity.id))fail('Physician/clinic/WebPage authority topology broken');
const offered=new Set([...refs(person.availableService),...refs(clinic.availableService)]),registered=new Set(registry.services.filter(x=>x.publishable).map(x=>x.id));for(const x of registered)if(!offered.has(x))fail(`Registry service not projected ${x}`);for(const x of offered)if(!registered.has(x))fail(`Projected service missing registry ${x}`);if(![...registered].some(x=>x.includes('botulinum-toxin-chronic-migraine')))fail('Migraine Botox offering missing');for(const sid of offered){const s=byId.get(sid);if(!s||!types(s).includes('Service')||!refs(s.provider).includes(release.primaryEntity.id))fail(`Service provider/type drift ${sid}`)}
for(const r of answerRegistry.answers){const q=byId.get(r.questionId),a=byId.get(r.answerId);if(!q||!a||id(q.acceptedAnswer)!==r.answerId)fail(`Answer atom drift ${r.questionId}`)}
const expectedRating=Number(volatile.rating),expectedCount=Number(volatile.reviewCount);if(live.about?.['@id']!==release.clinic.id||live.item?.['@id']!==release.clinic.id||live.dateModified!==volatile.valueObservedAt)fail('Live observation target/timestamp drift');const props=arr(live.item?.additionalProperty),rating=Number(props.find(x=>x.propertyID==='Google Places rating')?.value),count=Number(props.find(x=>x.propertyID==='Google Places userRatingCount')?.value);if(rating!==expectedRating||count!==expectedCount)fail('Live observation value drift');
for(const [k,v] of Object.entries({release:release.release,conceptDoi:release.dataset.zenodo.conceptDoi,versionDoi:release.dataset.zenodo.versionDoi,recordId:String(release.dataset.zenodo.recordId),datasetIri:release.dataset.id,personWikidata:release.primaryEntity.wikidata,clinicWikidata:release.dataset.supportingClinicWikidata,datasetWikidata:release.dataset.wikidata}))if(String(matrix[k])!==String(v))fail(`Current release matrix drift ${k}`);if(matrix.reputation?.rating!==expectedRating||matrix.reputation?.reviewCount!==expectedCount)fail('Current release matrix reputation drift');
const qlines=(await readFile(path.join(dist,'query-matrix.jsonl'),'utf8')).trim().split('\n').filter(Boolean).map(JSON.parse);const unique=new Set();for(const row of qlines){const key=`${row.language}|${row.query}`;if(unique.has(key))fail(`Duplicate Query Matrix row ${key}`);unique.add(key);if(row.preferred_entity!==release.primaryEntity.wikidata||row.dataset_iri!==release.dataset.id||row.release!==release.release||row.version_doi!==release.dataset.zenodo.versionDoi||row.retrieval_priority!==queryPolicy.retrievalPriority||row.positioning_mode!==queryPolicy.positioningMode)fail(`Query Matrix authority drift ${key}`)}for(const l of queryPolicy.languages)if(!qlines.some(r=>r.language===l))fail(`Query Matrix language missing ${l}`);for(const s of queryPolicy.scopes)if(!qlines.some(r=>r.query_scope===s))fail(`Query Matrix scope missing ${s}`);for(const i of queryPolicy.intentFamilies)if(!qlines.some(r=>r.intent_family===i))fail(`Query Matrix intent missing ${i}`);if(qlines.length<queryPolicy.languages.length*queryPolicy.scopes.length*queryPolicy.intentFamilies.length)fail('Query Matrix coverage unexpectedly sparse');
if(manifest.release!==release.release||manifest.baseRelease!==release.release||manifest.dataset?.versionDoi!==release.dataset.zenodo.versionDoi||manifest.review?.date!==release.medicalReviewedAt||manifest.liveObservation?.reviewCount!==expectedCount)fail('Current-serving manifest release/review drift');for(const [rel,meta] of Object.entries(manifest.files||{})){const p=path.join(dist,rel);await access(p);const b=await readFile(p);if(b.length!==meta.bytes||sha(b)!==meta.sha256)fail(`Manifest file bytes/hash drift ${rel}`)}if(manifest.invariants?.rootHtmlSha256!==sha(Buffer.from(html)))fail('Manifest root HTML hash drift');
if(att.baseRelease!==release.release||att.indexHtmlSha256!==sha(Buffer.from(html))||att.artifactManifestSha256!==sha(manifestBytes)||att.liveObservationSha256!==sha(liveBytes)||att.headersSha256!==sha(Buffer.from(headers))||att.versionDoi!==release.dataset.zenodo.versionDoi)fail('Live-serving attestation drift');
const digestFor=route=>{const lines=headers.split(/\r?\n/),i=lines.findIndex(x=>x===`/${route}`);if(i<0)return null;for(let j=i+1;j<lines.length&&/^  /.test(lines[j]);j++){const m=lines[j].match(/^  Repr-Digest: sha-256=:([^:]+):$/);if(m)return m[1]}return null};for(const route of ['artifact-manifest.json','live-observations.jsonld','query-matrix.jsonl','current-release-matrix.json','datapackage.json','croissant.json','dcat.ttl','linkset.json']){const d=digestFor(route);if(!d||d!==b64(await readFile(path.join(dist,route))))fail(`Header Repr-Digest drift ${route}`)}
const redirects=await readFile(path.join(dist,'_redirects'),'utf8'),sources=new Set();for(const line of redirects.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){const [from,to,code]=line.split(/\s+/);if(code!=='301'||sources.has(from))fail(`Redirect contract drift ${line}`);sources.add(from);if(to.includes('#')){const frag=decodeURIComponent(to.split('#')[1]||'');if(frag&&!html.includes(`id="${frag}"`)&&!html.includes(`id='${frag}'`))fail(`Redirect target fragment absent ${line}`)}}
const sitemapLocs=[...sitemap.matchAll(/<loc>([^<]+)<\/loc>/g)].map(m=>m[1]);if(sitemapLocs.length!==1||sitemapLocs[0]!==release.canonicalUrl)fail('Sitemap must contain only canonical HTML landing');if(!graphText.includes(release.dataset.zenodo.conceptDoi)||!graphText.includes(release.dataset.zenodo.versionDoi))fail('Graph DOI topology incomplete');
console.log(JSON.stringify({stage:'DIST_SEMANTIC_AND_SERVING_CONTRACT',release:release.release,htmlBytes,graphNodes:nodes.length,services:registered.size,answers:answerRegistry.answers.length,queryRows:qlines.length,supportNodes:supportIds.size,liveReputation:{rating,count,observedAt:volatile.valueObservedAt},manifestFiles:Object.keys(manifest.files||{}).length,integrity:'PASS'},null,2));
