import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {parse,serialize} from 'parse5';
const moduleUrl=new URL('../src/lib/jsonld.mjs',import.meta.url);
assert(await fs.access(moduleUrl).then(()=>true,()=>false),'Central HTML-safe JSON-LD serializer is required');
const {serializeInlineJsonLd}=await import(moduleUrl);
const {semanticFingerprint,rdfFingerprint}=await import('./lib/rdf.mjs');
const original={'@context':{'@vocab':'https://schema.org/'},'@id':'https://example.org/entity',name:'literal </script><script>alert(1)</script> & \u2028 \u2029'};
const html=parse('<html><head><script type="application/ld+json">'+serializeInlineJsonLd(original)+'</script></head><body></body></html>');
const nodes=[];function walk(n){nodes.push(n);for(const c of n.childNodes??[])walk(c);}walk(html);
const scripts=nodes.filter(n=>n.tagName==='script');assert.equal(scripts.length,1,'Only the intended script exists');
assert.deepEqual(JSON.parse(serialize(scripts[0])),original,'JSON extraction preserves literal semantic text');
const shuffled={name:original.name,'@id':original['@id'],'@context':original['@context']};
assert.equal(await semanticFingerprint(original),await semanticFingerprint(shuffled),'Fingerprint ignores JSON key order');
assert.notEqual(await semanticFingerprint(original),await semanticFingerprint({...original,name:'changed'}),'Fingerprint detects changed RDF truth');
assert.equal(await semanticFingerprint(original),await rdfFingerprint('<https://example.org/entity> <https://schema.org/name> '+JSON.stringify(original.name)+' .\n'),'RDF and JSON-LD fingerprints agree');
console.log('Safe inline JSON-LD and RDFC-1.0 PASS');
