PREFIX schema: <https://schema.org/>

SELECT ?clinic ?gap WHERE {
  BIND(<https://www.ghezelbaash.ir/#clinic> AS ?clinic)
  {
    BIND("address" AS ?gap)
    FILTER NOT EXISTS { ?clinic schema:address ?address . }
  }
  UNION
  {
    BIND("geo" AS ?gap)
    FILTER NOT EXISTS { ?clinic schema:geo ?geo . }
  }
  UNION
  {
    BIND("telephone" AS ?gap)
    FILTER NOT EXISTS { ?clinic schema:telephone ?telephone . }
  }
  UNION
  {
    BIND("map" AS ?gap)
    FILTER NOT EXISTS { ?clinic schema:hasMap ?map . }
  }
}
