PREFIX schema: <https://schema.org/>

SELECT ?term WHERE {
  ?term a schema:DefinedTerm .
  FILTER(STRSTARTS(STR(?term), "https://www.ghezelbaash.ir/kg/aesthetic-scope#"))
  FILTER(!CONTAINS(STR(?term), "#group-"))
  FILTER NOT EXISTS { <https://www.ghezelbaash.ir/#dr-saeed-ghezelbash> schema:knowsAbout ?term . }
}
