PREFIX schema: <https://schema.org/>

SELECT ?doctor ?clinic WHERE {
  BIND(<https://www.ghezelbaash.ir/#dr-saeed-ghezelbash> AS ?doctor)
  BIND(<https://www.ghezelbaash.ir/#clinic> AS ?clinic)
  FILTER NOT EXISTS { ?doctor schema:worksFor ?clinic . }
  FILTER NOT EXISTS { ?doctor schema:affiliation ?clinic . }
  FILTER NOT EXISTS { ?clinic schema:employee ?doctor . }
  FILTER NOT EXISTS { ?clinic schema:founder ?doctor . }
}
