PREFIX schema: <https://schema.org/>

SELECT ?page ?reviewer WHERE {
  ?page a schema:MedicalWebPage .
  ?page schema:reviewedBy ?reviewer .
  FILTER(?reviewer != <https://www.ghezelbaash.ir/#dr-saeed-ghezelbash>)
}
