PREFIX schema: <https://schema.org/>

SELECT ?entity WHERE {
  VALUES ?entity { <https://www.ghezelbaash.ir/#dr-saeed-ghezelbash> <https://www.ghezelbaash.ir/#physician> }
  FILTER NOT EXISTS {
    ?entity schema:identifier ?identifier .
    ?identifier schema:propertyID ?propertyID .
    ?identifier schema:value ?value .
  }
}
