PREFIX schema: <https://schema.org/>

SELECT ?term WHERE {
  ?term a schema:DefinedTerm .
  FILTER(STRSTARTS(STR(?term), "https://www.ghezelbaash.ir/kg/aesthetic-scope#"))
  FILTER NOT EXISTS { ?term schema:inDefinedTermSet <https://www.ghezelbaash.ir/kg/aesthetic-scope#term-set> . }
}
