site:
  name: کلینیک زیبایی دکتر سعید قزلباش
  site: 'https://www.ghezelbaash.ir'
  base: '/'
  trailingSlash: true

  googleSiteVerificationId: 8n4oKDWVkFyp-dUWoTAnLVO1HTr4ARpSPEVngAvybCQ

metadata:
  title:
    default: دکتر سعید قزلباش | کلینیک زیبایی در کرمانشاه
    template: '%s | دکتر سعید قزلباش'
  description: 'وب‌سایت رسمی کلینیک زیبایی دکتر سعید قزلباش در کرمانشاه؛ معرفی خدمات بوتاکس، فیلر، لیفت نخ و درمان مشکلات زیبایی با مسیر رسمی تماس و هماهنگی.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: کلینیک زیبایی دکتر سعید قزلباش
    images:
      - url: '/og/home.jpg'
        width: 1200
        height: 630
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: fa-IR
  textDirection: rtl

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%/'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 0

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'light'
