name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: firebase-hosting
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ghezelbaash-kg --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
